package com.ami.ec.channel.dao.officialPlugin;

import com.ami.ec.channel.domain.officialPlugin.SellerCategory;
import com.ami.ec.channel.domain.officialPlugin.SellerCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SellerCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    int countByExample(SellerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    int deleteByExample(SellerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    int insert(SellerCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    int insertSelective(SellerCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    List<SellerCategory> selectByExample(SellerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SellerCategory record, @Param("example") SellerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Seller_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SellerCategory record, @Param("example") SellerCategoryExample example);
}