package com.ami.ifs.dao;

import com.ami.ifs.dao.IfsKey;
import com.ami.ifs.dao.IfsKeyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IfsKeyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int countByExample(IfsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int deleteByExample(IfsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ifsKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int insert(IfsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int insertSelective(IfsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    List<IfsKey> selectByExample(IfsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    IfsKey selectByPrimaryKey(Integer ifsKeyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IfsKey record, @Param("example") IfsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IfsKey record, @Param("example") IfsKeyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IfsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Key
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IfsKey record);
}