package com.ami.ec.channel.dao.asp;

import com.ami.ec.channel.domain.asp.AspIfsIUnitItemMaster;
import com.ami.ec.channel.domain.asp.AspIfsIUnitItemMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AspIfsIUnitItemMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    int countByExample(AspIfsIUnitItemMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    int deleteByExample(AspIfsIUnitItemMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    int insert(AspIfsIUnitItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    int insertSelective(AspIfsIUnitItemMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    List<AspIfsIUnitItemMaster> selectByExample(AspIfsIUnitItemMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AspIfsIUnitItemMaster record, @Param("example") AspIfsIUnitItemMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_item_master
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AspIfsIUnitItemMaster record, @Param("example") AspIfsIUnitItemMasterExample example);
}