package com.ami.ifs.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IfsStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public IfsStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStatusIdIsNull() {
            addCriterion("Status_Id is null");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNotNull() {
            addCriterion("Status_Id is not null");
            return (Criteria) this;
        }

        public Criteria andStatusIdEqualTo(Long value) {
            addCriterion("Status_Id =", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotEqualTo(Long value) {
            addCriterion("Status_Id <>", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThan(Long value) {
            addCriterion("Status_Id >", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Status_Id >=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThan(Long value) {
            addCriterion("Status_Id <", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThanOrEqualTo(Long value) {
            addCriterion("Status_Id <=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdIn(List<Long> values) {
            addCriterion("Status_Id in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotIn(List<Long> values) {
            addCriterion("Status_Id not in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdBetween(Long value1, Long value2) {
            addCriterion("Status_Id between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotBetween(Long value1, Long value2) {
            addCriterion("Status_Id not between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNull() {
            addCriterion("Unit_Id is null");
            return (Criteria) this;
        }

        public Criteria andUnitIdIsNotNull() {
            addCriterion("Unit_Id is not null");
            return (Criteria) this;
        }

        public Criteria andUnitIdEqualTo(Long value) {
            addCriterion("Unit_Id =", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotEqualTo(Long value) {
            addCriterion("Unit_Id <>", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThan(Long value) {
            addCriterion("Unit_Id >", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Unit_Id >=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThan(Long value) {
            addCriterion("Unit_Id <", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdLessThanOrEqualTo(Long value) {
            addCriterion("Unit_Id <=", value, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdIn(List<Long> values) {
            addCriterion("Unit_Id in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotIn(List<Long> values) {
            addCriterion("Unit_Id not in", values, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdBetween(Long value1, Long value2) {
            addCriterion("Unit_Id between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andUnitIdNotBetween(Long value1, Long value2) {
            addCriterion("Unit_Id not between", value1, value2, "unitId");
            return (Criteria) this;
        }

        public Criteria andStatusNoIsNull() {
            addCriterion("Status_No is null");
            return (Criteria) this;
        }

        public Criteria andStatusNoIsNotNull() {
            addCriterion("Status_No is not null");
            return (Criteria) this;
        }

        public Criteria andStatusNoEqualTo(Short value) {
            addCriterion("Status_No =", value, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoNotEqualTo(Short value) {
            addCriterion("Status_No <>", value, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoGreaterThan(Short value) {
            addCriterion("Status_No >", value, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoGreaterThanOrEqualTo(Short value) {
            addCriterion("Status_No >=", value, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoLessThan(Short value) {
            addCriterion("Status_No <", value, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoLessThanOrEqualTo(Short value) {
            addCriterion("Status_No <=", value, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoIn(List<Short> values) {
            addCriterion("Status_No in", values, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoNotIn(List<Short> values) {
            addCriterion("Status_No not in", values, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoBetween(Short value1, Short value2) {
            addCriterion("Status_No between", value1, value2, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusNoNotBetween(Short value1, Short value2) {
            addCriterion("Status_No not between", value1, value2, "statusNo");
            return (Criteria) this;
        }

        public Criteria andStatusForIsNull() {
            addCriterion("Status_For is null");
            return (Criteria) this;
        }

        public Criteria andStatusForIsNotNull() {
            addCriterion("Status_For is not null");
            return (Criteria) this;
        }

        public Criteria andStatusForEqualTo(String value) {
            addCriterion("Status_For =", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForNotEqualTo(String value) {
            addCriterion("Status_For <>", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForGreaterThan(String value) {
            addCriterion("Status_For >", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForGreaterThanOrEqualTo(String value) {
            addCriterion("Status_For >=", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForLessThan(String value) {
            addCriterion("Status_For <", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForLessThanOrEqualTo(String value) {
            addCriterion("Status_For <=", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForLike(String value) {
            addCriterion("Status_For like", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForNotLike(String value) {
            addCriterion("Status_For not like", value, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForIn(List<String> values) {
            addCriterion("Status_For in", values, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForNotIn(List<String> values) {
            addCriterion("Status_For not in", values, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForBetween(String value1, String value2) {
            addCriterion("Status_For between", value1, value2, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusForNotBetween(String value1, String value2) {
            addCriterion("Status_For not between", value1, value2, "statusFor");
            return (Criteria) this;
        }

        public Criteria andStatusValueIsNull() {
            addCriterion("Status_Value is null");
            return (Criteria) this;
        }

        public Criteria andStatusValueIsNotNull() {
            addCriterion("Status_Value is not null");
            return (Criteria) this;
        }

        public Criteria andStatusValueEqualTo(String value) {
            addCriterion("Status_Value =", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueNotEqualTo(String value) {
            addCriterion("Status_Value <>", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueGreaterThan(String value) {
            addCriterion("Status_Value >", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueGreaterThanOrEqualTo(String value) {
            addCriterion("Status_Value >=", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueLessThan(String value) {
            addCriterion("Status_Value <", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueLessThanOrEqualTo(String value) {
            addCriterion("Status_Value <=", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueLike(String value) {
            addCriterion("Status_Value like", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueNotLike(String value) {
            addCriterion("Status_Value not like", value, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueIn(List<String> values) {
            addCriterion("Status_Value in", values, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueNotIn(List<String> values) {
            addCriterion("Status_Value not in", values, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueBetween(String value1, String value2) {
            addCriterion("Status_Value between", value1, value2, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusValueNotBetween(String value1, String value2) {
            addCriterion("Status_Value not between", value1, value2, "statusValue");
            return (Criteria) this;
        }

        public Criteria andStatusNameIsNull() {
            addCriterion("Status_Name is null");
            return (Criteria) this;
        }

        public Criteria andStatusNameIsNotNull() {
            addCriterion("Status_Name is not null");
            return (Criteria) this;
        }

        public Criteria andStatusNameEqualTo(String value) {
            addCriterion("Status_Name =", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameNotEqualTo(String value) {
            addCriterion("Status_Name <>", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameGreaterThan(String value) {
            addCriterion("Status_Name >", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameGreaterThanOrEqualTo(String value) {
            addCriterion("Status_Name >=", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameLessThan(String value) {
            addCriterion("Status_Name <", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameLessThanOrEqualTo(String value) {
            addCriterion("Status_Name <=", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameLike(String value) {
            addCriterion("Status_Name like", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameNotLike(String value) {
            addCriterion("Status_Name not like", value, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameIn(List<String> values) {
            addCriterion("Status_Name in", values, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameNotIn(List<String> values) {
            addCriterion("Status_Name not in", values, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameBetween(String value1, String value2) {
            addCriterion("Status_Name between", value1, value2, "statusName");
            return (Criteria) this;
        }

        public Criteria andStatusNameNotBetween(String value1, String value2) {
            addCriterion("Status_Name not between", value1, value2, "statusName");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("Operate_Time is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("Operate_Time is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("Operate_Time =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("Operate_Time <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("Operate_Time >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Operate_Time >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("Operate_Time <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Operate_Time <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("Operate_Time in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("Operate_Time not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("Operate_Time between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Operate_Time not between", value1, value2, "operateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ifs_Status
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Ifs_Status
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}