package com.ami.ec.channel.dao.pluginManager;

import com.ami.ec.channel.domain.pluginManager.CommonLog;
import com.ami.ec.channel.domain.pluginManager.CommonLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommonLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int countByExample(CommonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int deleteByExample(CommonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int insert(CommonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int insertSelective(CommonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    List<CommonLog> selectByExample(CommonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    CommonLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommonLog record, @Param("example") CommonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommonLog record, @Param("example") CommonLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommonLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Common_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommonLog record);
}