package com.ami.ec.channel.dao.asp;

import com.ami.ec.channel.domain.asp.AspIfsIUnitSkuMaster;
import com.ami.ec.channel.domain.asp.AspIfsIUnitSkuMasterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AspIfsIUnitSkuMasterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    int countByExample(AspIfsIUnitSkuMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    int deleteByExample(AspIfsIUnitSkuMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    int insert(AspIfsIUnitSkuMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    int insertSelective(AspIfsIUnitSkuMaster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    List<AspIfsIUnitSkuMaster> selectByExample(AspIfsIUnitSkuMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AspIfsIUnitSkuMaster record, @Param("example") AspIfsIUnitSkuMasterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_unit_sku_master
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AspIfsIUnitSkuMaster record, @Param("example") AspIfsIUnitSkuMasterExample example);
}