package com.ami.ec.channel.domain.pluginManager;

import java.util.Date;

public class IfDefine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_id
     *
     * @mbggenerated
     */
    private Integer ifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_code
     *
     * @mbggenerated
     */
    private String ifCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_name
     *
     * @mbggenerated
     */
    private String ifName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_cat
     *
     * @mbggenerated
     */
    private String ifCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_sub_cat
     *
     * @mbggenerated
     */
    private String ifSubCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Is_parent
     *
     * @mbggenerated
     */
    private Boolean isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Pj_id
     *
     * @mbggenerated
     */
    private Long pjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Store_id
     *
     * @mbggenerated
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Role_id
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Process_index
     *
     * @mbggenerated
     */
    private Integer processIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Bat_no_pre
     *
     * @mbggenerated
     */
    private String batNoPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Bat_no_length
     *
     * @mbggenerated
     */
    private Integer batNoLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Bat_no_current
     *
     * @mbggenerated
     */
    private Integer batNoCurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Operate_user_id
     *
     * @mbggenerated
     */
    private Long operateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Thread_num
     *
     * @mbggenerated
     */
    private Integer threadNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_prop_1
     *
     * @mbggenerated
     */
    private String ifProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_prop_2
     *
     * @mbggenerated
     */
    private String ifProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_prop_3
     *
     * @mbggenerated
     */
    private String ifProp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_qty_1
     *
     * @mbggenerated
     */
    private Integer ifQty1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_qty_2
     *
     * @mbggenerated
     */
    private Integer ifQty2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_qty_3
     *
     * @mbggenerated
     */
    private Integer ifQty3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_time_1
     *
     * @mbggenerated
     */
    private Date ifTime1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_time_2
     *
     * @mbggenerated
     */
    private Date ifTime2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.IF_time_3
     *
     * @mbggenerated
     */
    private Date ifTime3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.No_data_retry_times
     *
     * @mbggenerated
     */
    private Integer noDataRetryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Not_data_retry_to_seconds
     *
     * @mbggenerated
     */
    private Integer notDataRetryToSeconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Error_retry_times
     *
     * @mbggenerated
     */
    private Integer errorRetryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Error_retry_to_seconds
     *
     * @mbggenerated
     */
    private Integer errorRetryToSeconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Retry_wait_seconds
     *
     * @mbggenerated
     */
    private Integer retryWaitSeconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Retry_type
     *
     * @mbggenerated
     */
    private String retryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Fail_continue
     *
     * @mbggenerated
     */
    private Boolean failContinue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Wait_time_out
     *
     * @mbggenerated
     */
    private Integer waitTimeOut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Time_out_continue
     *
     * @mbggenerated
     */
    private Boolean timeOutContinue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IF_define.Time_stamp
     *
     * @mbggenerated
     */
    private byte[] timeStamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_id
     *
     * @return the value of IF_define.IF_id
     *
     * @mbggenerated
     */
    public Integer getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_id
     *
     * @param ifId the value for IF_define.IF_id
     *
     * @mbggenerated
     */
    public void setIfId(Integer ifId) {
        this.ifId = ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_code
     *
     * @return the value of IF_define.IF_code
     *
     * @mbggenerated
     */
    public String getIfCode() {
        return ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_code
     *
     * @param ifCode the value for IF_define.IF_code
     *
     * @mbggenerated
     */
    public void setIfCode(String ifCode) {
        this.ifCode = ifCode == null ? null : ifCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_name
     *
     * @return the value of IF_define.IF_name
     *
     * @mbggenerated
     */
    public String getIfName() {
        return ifName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_name
     *
     * @param ifName the value for IF_define.IF_name
     *
     * @mbggenerated
     */
    public void setIfName(String ifName) {
        this.ifName = ifName == null ? null : ifName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_cat
     *
     * @return the value of IF_define.IF_cat
     *
     * @mbggenerated
     */
    public String getIfCat() {
        return ifCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_cat
     *
     * @param ifCat the value for IF_define.IF_cat
     *
     * @mbggenerated
     */
    public void setIfCat(String ifCat) {
        this.ifCat = ifCat == null ? null : ifCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_sub_cat
     *
     * @return the value of IF_define.IF_sub_cat
     *
     * @mbggenerated
     */
    public String getIfSubCat() {
        return ifSubCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_sub_cat
     *
     * @param ifSubCat the value for IF_define.IF_sub_cat
     *
     * @mbggenerated
     */
    public void setIfSubCat(String ifSubCat) {
        this.ifSubCat = ifSubCat == null ? null : ifSubCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Is_parent
     *
     * @return the value of IF_define.Is_parent
     *
     * @mbggenerated
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Is_parent
     *
     * @param isParent the value for IF_define.Is_parent
     *
     * @mbggenerated
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Parent_id
     *
     * @return the value of IF_define.Parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Parent_id
     *
     * @param parentId the value for IF_define.Parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Pj_id
     *
     * @return the value of IF_define.Pj_id
     *
     * @mbggenerated
     */
    public Long getPjId() {
        return pjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Pj_id
     *
     * @param pjId the value for IF_define.Pj_id
     *
     * @mbggenerated
     */
    public void setPjId(Long pjId) {
        this.pjId = pjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Store_id
     *
     * @return the value of IF_define.Store_id
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Store_id
     *
     * @param storeId the value for IF_define.Store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Role_id
     *
     * @return the value of IF_define.Role_id
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Role_id
     *
     * @param roleId the value for IF_define.Role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Process_index
     *
     * @return the value of IF_define.Process_index
     *
     * @mbggenerated
     */
    public Integer getProcessIndex() {
        return processIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Process_index
     *
     * @param processIndex the value for IF_define.Process_index
     *
     * @mbggenerated
     */
    public void setProcessIndex(Integer processIndex) {
        this.processIndex = processIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Bat_no_pre
     *
     * @return the value of IF_define.Bat_no_pre
     *
     * @mbggenerated
     */
    public String getBatNoPre() {
        return batNoPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Bat_no_pre
     *
     * @param batNoPre the value for IF_define.Bat_no_pre
     *
     * @mbggenerated
     */
    public void setBatNoPre(String batNoPre) {
        this.batNoPre = batNoPre == null ? null : batNoPre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Bat_no_length
     *
     * @return the value of IF_define.Bat_no_length
     *
     * @mbggenerated
     */
    public Integer getBatNoLength() {
        return batNoLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Bat_no_length
     *
     * @param batNoLength the value for IF_define.Bat_no_length
     *
     * @mbggenerated
     */
    public void setBatNoLength(Integer batNoLength) {
        this.batNoLength = batNoLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Bat_no_current
     *
     * @return the value of IF_define.Bat_no_current
     *
     * @mbggenerated
     */
    public Integer getBatNoCurrent() {
        return batNoCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Bat_no_current
     *
     * @param batNoCurrent the value for IF_define.Bat_no_current
     *
     * @mbggenerated
     */
    public void setBatNoCurrent(Integer batNoCurrent) {
        this.batNoCurrent = batNoCurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Operate_user_id
     *
     * @return the value of IF_define.Operate_user_id
     *
     * @mbggenerated
     */
    public Long getOperateUserId() {
        return operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Operate_user_id
     *
     * @param operateUserId the value for IF_define.Operate_user_id
     *
     * @mbggenerated
     */
    public void setOperateUserId(Long operateUserId) {
        this.operateUserId = operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Operate_time
     *
     * @return the value of IF_define.Operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Operate_time
     *
     * @param operateTime the value for IF_define.Operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Create_time
     *
     * @return the value of IF_define.Create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Create_time
     *
     * @param createTime the value for IF_define.Create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Thread_num
     *
     * @return the value of IF_define.Thread_num
     *
     * @mbggenerated
     */
    public Integer getThreadNum() {
        return threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Thread_num
     *
     * @param threadNum the value for IF_define.Thread_num
     *
     * @mbggenerated
     */
    public void setThreadNum(Integer threadNum) {
        this.threadNum = threadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Status
     *
     * @return the value of IF_define.Status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Status
     *
     * @param status the value for IF_define.Status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_prop_1
     *
     * @return the value of IF_define.IF_prop_1
     *
     * @mbggenerated
     */
    public String getIfProp1() {
        return ifProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_prop_1
     *
     * @param ifProp1 the value for IF_define.IF_prop_1
     *
     * @mbggenerated
     */
    public void setIfProp1(String ifProp1) {
        this.ifProp1 = ifProp1 == null ? null : ifProp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_prop_2
     *
     * @return the value of IF_define.IF_prop_2
     *
     * @mbggenerated
     */
    public String getIfProp2() {
        return ifProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_prop_2
     *
     * @param ifProp2 the value for IF_define.IF_prop_2
     *
     * @mbggenerated
     */
    public void setIfProp2(String ifProp2) {
        this.ifProp2 = ifProp2 == null ? null : ifProp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_prop_3
     *
     * @return the value of IF_define.IF_prop_3
     *
     * @mbggenerated
     */
    public String getIfProp3() {
        return ifProp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_prop_3
     *
     * @param ifProp3 the value for IF_define.IF_prop_3
     *
     * @mbggenerated
     */
    public void setIfProp3(String ifProp3) {
        this.ifProp3 = ifProp3 == null ? null : ifProp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_qty_1
     *
     * @return the value of IF_define.IF_qty_1
     *
     * @mbggenerated
     */
    public Integer getIfQty1() {
        return ifQty1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_qty_1
     *
     * @param ifQty1 the value for IF_define.IF_qty_1
     *
     * @mbggenerated
     */
    public void setIfQty1(Integer ifQty1) {
        this.ifQty1 = ifQty1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_qty_2
     *
     * @return the value of IF_define.IF_qty_2
     *
     * @mbggenerated
     */
    public Integer getIfQty2() {
        return ifQty2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_qty_2
     *
     * @param ifQty2 the value for IF_define.IF_qty_2
     *
     * @mbggenerated
     */
    public void setIfQty2(Integer ifQty2) {
        this.ifQty2 = ifQty2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_qty_3
     *
     * @return the value of IF_define.IF_qty_3
     *
     * @mbggenerated
     */
    public Integer getIfQty3() {
        return ifQty3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_qty_3
     *
     * @param ifQty3 the value for IF_define.IF_qty_3
     *
     * @mbggenerated
     */
    public void setIfQty3(Integer ifQty3) {
        this.ifQty3 = ifQty3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_time_1
     *
     * @return the value of IF_define.IF_time_1
     *
     * @mbggenerated
     */
    public Date getIfTime1() {
        return ifTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_time_1
     *
     * @param ifTime1 the value for IF_define.IF_time_1
     *
     * @mbggenerated
     */
    public void setIfTime1(Date ifTime1) {
        this.ifTime1 = ifTime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_time_2
     *
     * @return the value of IF_define.IF_time_2
     *
     * @mbggenerated
     */
    public Date getIfTime2() {
        return ifTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_time_2
     *
     * @param ifTime2 the value for IF_define.IF_time_2
     *
     * @mbggenerated
     */
    public void setIfTime2(Date ifTime2) {
        this.ifTime2 = ifTime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.IF_time_3
     *
     * @return the value of IF_define.IF_time_3
     *
     * @mbggenerated
     */
    public Date getIfTime3() {
        return ifTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.IF_time_3
     *
     * @param ifTime3 the value for IF_define.IF_time_3
     *
     * @mbggenerated
     */
    public void setIfTime3(Date ifTime3) {
        this.ifTime3 = ifTime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.No_data_retry_times
     *
     * @return the value of IF_define.No_data_retry_times
     *
     * @mbggenerated
     */
    public Integer getNoDataRetryTimes() {
        return noDataRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.No_data_retry_times
     *
     * @param noDataRetryTimes the value for IF_define.No_data_retry_times
     *
     * @mbggenerated
     */
    public void setNoDataRetryTimes(Integer noDataRetryTimes) {
        this.noDataRetryTimes = noDataRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Not_data_retry_to_seconds
     *
     * @return the value of IF_define.Not_data_retry_to_seconds
     *
     * @mbggenerated
     */
    public Integer getNotDataRetryToSeconds() {
        return notDataRetryToSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Not_data_retry_to_seconds
     *
     * @param notDataRetryToSeconds the value for IF_define.Not_data_retry_to_seconds
     *
     * @mbggenerated
     */
    public void setNotDataRetryToSeconds(Integer notDataRetryToSeconds) {
        this.notDataRetryToSeconds = notDataRetryToSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Error_retry_times
     *
     * @return the value of IF_define.Error_retry_times
     *
     * @mbggenerated
     */
    public Integer getErrorRetryTimes() {
        return errorRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Error_retry_times
     *
     * @param errorRetryTimes the value for IF_define.Error_retry_times
     *
     * @mbggenerated
     */
    public void setErrorRetryTimes(Integer errorRetryTimes) {
        this.errorRetryTimes = errorRetryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Error_retry_to_seconds
     *
     * @return the value of IF_define.Error_retry_to_seconds
     *
     * @mbggenerated
     */
    public Integer getErrorRetryToSeconds() {
        return errorRetryToSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Error_retry_to_seconds
     *
     * @param errorRetryToSeconds the value for IF_define.Error_retry_to_seconds
     *
     * @mbggenerated
     */
    public void setErrorRetryToSeconds(Integer errorRetryToSeconds) {
        this.errorRetryToSeconds = errorRetryToSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Retry_wait_seconds
     *
     * @return the value of IF_define.Retry_wait_seconds
     *
     * @mbggenerated
     */
    public Integer getRetryWaitSeconds() {
        return retryWaitSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Retry_wait_seconds
     *
     * @param retryWaitSeconds the value for IF_define.Retry_wait_seconds
     *
     * @mbggenerated
     */
    public void setRetryWaitSeconds(Integer retryWaitSeconds) {
        this.retryWaitSeconds = retryWaitSeconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Retry_type
     *
     * @return the value of IF_define.Retry_type
     *
     * @mbggenerated
     */
    public String getRetryType() {
        return retryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Retry_type
     *
     * @param retryType the value for IF_define.Retry_type
     *
     * @mbggenerated
     */
    public void setRetryType(String retryType) {
        this.retryType = retryType == null ? null : retryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Fail_continue
     *
     * @return the value of IF_define.Fail_continue
     *
     * @mbggenerated
     */
    public Boolean getFailContinue() {
        return failContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Fail_continue
     *
     * @param failContinue the value for IF_define.Fail_continue
     *
     * @mbggenerated
     */
    public void setFailContinue(Boolean failContinue) {
        this.failContinue = failContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Wait_time_out
     *
     * @return the value of IF_define.Wait_time_out
     *
     * @mbggenerated
     */
    public Integer getWaitTimeOut() {
        return waitTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Wait_time_out
     *
     * @param waitTimeOut the value for IF_define.Wait_time_out
     *
     * @mbggenerated
     */
    public void setWaitTimeOut(Integer waitTimeOut) {
        this.waitTimeOut = waitTimeOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Time_out_continue
     *
     * @return the value of IF_define.Time_out_continue
     *
     * @mbggenerated
     */
    public Boolean getTimeOutContinue() {
        return timeOutContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Time_out_continue
     *
     * @param timeOutContinue the value for IF_define.Time_out_continue
     *
     * @mbggenerated
     */
    public void setTimeOutContinue(Boolean timeOutContinue) {
        this.timeOutContinue = timeOutContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IF_define.Time_stamp
     *
     * @return the value of IF_define.Time_stamp
     *
     * @mbggenerated
     */
    public byte[] getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IF_define.Time_stamp
     *
     * @param timeStamp the value for IF_define.Time_stamp
     *
     * @mbggenerated
     */
    public void setTimeStamp(byte[] timeStamp) {
        this.timeStamp = timeStamp;
    }
}