package com.ami.ec.channel.domain.asp;

import java.math.BigDecimal;
import java.util.Date;

public class AspIfsIUnitItemMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Exec_flag
     *
     * @mbggenerated
     */
    private Short execFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Store_Id
     *
     * @mbggenerated
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Operate_Type
     *
     * @mbggenerated
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Ifs_A_Cd
     *
     * @mbggenerated
     */
    private String ifsACd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Ifs_C_Cd
     *
     * @mbggenerated
     */
    private String ifsCCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Operate_Time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Unit_Item_Id
     *
     * @mbggenerated
     */
    private String unitItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Item_Name
     *
     * @mbggenerated
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Item_Std_Price
     *
     * @mbggenerated
     */
    private BigDecimal itemStdPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Item_Price
     *
     * @mbggenerated
     */
    private BigDecimal itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Orig_Item_Type
     *
     * @mbggenerated
     */
    private String origItemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Item_Cd
     *
     * @mbggenerated
     */
    private String itemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_i_unit_item_master.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Exec_flag
     *
     * @return the value of Ifs_i_unit_item_master.Exec_flag
     *
     * @mbggenerated
     */
    public Short getExecFlag() {
        return execFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Exec_flag
     *
     * @param execFlag the value for Ifs_i_unit_item_master.Exec_flag
     *
     * @mbggenerated
     */
    public void setExecFlag(Short execFlag) {
        this.execFlag = execFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Store_Id
     *
     * @return the value of Ifs_i_unit_item_master.Store_Id
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Store_Id
     *
     * @param storeId the value for Ifs_i_unit_item_master.Store_Id
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Operate_Type
     *
     * @return the value of Ifs_i_unit_item_master.Operate_Type
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Operate_Type
     *
     * @param operateType the value for Ifs_i_unit_item_master.Operate_Type
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Ifs_A_Cd
     *
     * @return the value of Ifs_i_unit_item_master.Ifs_A_Cd
     *
     * @mbggenerated
     */
    public String getIfsACd() {
        return ifsACd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Ifs_A_Cd
     *
     * @param ifsACd the value for Ifs_i_unit_item_master.Ifs_A_Cd
     *
     * @mbggenerated
     */
    public void setIfsACd(String ifsACd) {
        this.ifsACd = ifsACd == null ? null : ifsACd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Ifs_C_Cd
     *
     * @return the value of Ifs_i_unit_item_master.Ifs_C_Cd
     *
     * @mbggenerated
     */
    public String getIfsCCd() {
        return ifsCCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Ifs_C_Cd
     *
     * @param ifsCCd the value for Ifs_i_unit_item_master.Ifs_C_Cd
     *
     * @mbggenerated
     */
    public void setIfsCCd(String ifsCCd) {
        this.ifsCCd = ifsCCd == null ? null : ifsCCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Operate_Time
     *
     * @return the value of Ifs_i_unit_item_master.Operate_Time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Operate_Time
     *
     * @param operateTime the value for Ifs_i_unit_item_master.Operate_Time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Timestamp
     *
     * @return the value of Ifs_i_unit_item_master.Timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Timestamp
     *
     * @param timestamp the value for Ifs_i_unit_item_master.Timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Unit_Item_Id
     *
     * @return the value of Ifs_i_unit_item_master.Unit_Item_Id
     *
     * @mbggenerated
     */
    public String getUnitItemId() {
        return unitItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Unit_Item_Id
     *
     * @param unitItemId the value for Ifs_i_unit_item_master.Unit_Item_Id
     *
     * @mbggenerated
     */
    public void setUnitItemId(String unitItemId) {
        this.unitItemId = unitItemId == null ? null : unitItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Item_Name
     *
     * @return the value of Ifs_i_unit_item_master.Item_Name
     *
     * @mbggenerated
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Item_Name
     *
     * @param itemName the value for Ifs_i_unit_item_master.Item_Name
     *
     * @mbggenerated
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Item_Std_Price
     *
     * @return the value of Ifs_i_unit_item_master.Item_Std_Price
     *
     * @mbggenerated
     */
    public BigDecimal getItemStdPrice() {
        return itemStdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Item_Std_Price
     *
     * @param itemStdPrice the value for Ifs_i_unit_item_master.Item_Std_Price
     *
     * @mbggenerated
     */
    public void setItemStdPrice(BigDecimal itemStdPrice) {
        this.itemStdPrice = itemStdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Item_Price
     *
     * @return the value of Ifs_i_unit_item_master.Item_Price
     *
     * @mbggenerated
     */
    public BigDecimal getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Item_Price
     *
     * @param itemPrice the value for Ifs_i_unit_item_master.Item_Price
     *
     * @mbggenerated
     */
    public void setItemPrice(BigDecimal itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Orig_Item_Type
     *
     * @return the value of Ifs_i_unit_item_master.Orig_Item_Type
     *
     * @mbggenerated
     */
    public String getOrigItemType() {
        return origItemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Orig_Item_Type
     *
     * @param origItemType the value for Ifs_i_unit_item_master.Orig_Item_Type
     *
     * @mbggenerated
     */
    public void setOrigItemType(String origItemType) {
        this.origItemType = origItemType == null ? null : origItemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Item_Cd
     *
     * @return the value of Ifs_i_unit_item_master.Item_Cd
     *
     * @mbggenerated
     */
    public String getItemCd() {
        return itemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Item_Cd
     *
     * @param itemCd the value for Ifs_i_unit_item_master.Item_Cd
     *
     * @mbggenerated
     */
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd == null ? null : itemCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_i_unit_item_master.Remark
     *
     * @return the value of Ifs_i_unit_item_master.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_i_unit_item_master.Remark
     *
     * @param remark the value for Ifs_i_unit_item_master.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}