package com.ami.ec.channel.dao.officialPlugin;

import com.ami.ec.channel.domain.officialPlugin.OfficialArticleTemp;
import com.ami.ec.channel.domain.officialPlugin.OfficialArticleTempExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OfficialArticleTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int countByExample(OfficialArticleTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int deleteByExample(OfficialArticleTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int insert(OfficialArticleTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int insertSelective(OfficialArticleTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    List<OfficialArticleTemp> selectByExample(OfficialArticleTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    OfficialArticleTemp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OfficialArticleTemp record, @Param("example") OfficialArticleTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OfficialArticleTemp record, @Param("example") OfficialArticleTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfficialArticleTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Official_article_temp
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfficialArticleTemp record);
}