package com.ami.ec.channel.dao.officialPlugin;

import com.ami.ec.channel.domain.officialPlugin.StatusMapping;
import com.ami.ec.channel.domain.officialPlugin.StatusMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatusMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    int countByExample(StatusMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    int deleteByExample(StatusMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    int insert(StatusMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    int insertSelective(StatusMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    List<StatusMapping> selectByExample(StatusMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StatusMapping record, @Param("example") StatusMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Status_mapping
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StatusMapping record, @Param("example") StatusMappingExample example);
}