package com.ami.ec.channel.domain.asp;

import java.util.Date;

public class AspIfsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Ifs_Key_Id
     *
     * @mbggenerated
     */
    private Integer ifsKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Ws_Key
     *
     * @mbggenerated
     */
    private String wsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Ifs_Cd
     *
     * @mbggenerated
     */
    private String ifsCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Ws_Type
     *
     * @mbggenerated
     */
    private String wsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Create_Time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Invalid_Time
     *
     * @mbggenerated
     */
    private Date invalidTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_key.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Ifs_Key_Id
     *
     * @return the value of Ifs_key.Ifs_Key_Id
     *
     * @mbggenerated
     */
    public Integer getIfsKeyId() {
        return ifsKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Ifs_Key_Id
     *
     * @param ifsKeyId the value for Ifs_key.Ifs_Key_Id
     *
     * @mbggenerated
     */
    public void setIfsKeyId(Integer ifsKeyId) {
        this.ifsKeyId = ifsKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Ws_Key
     *
     * @return the value of Ifs_key.Ws_Key
     *
     * @mbggenerated
     */
    public String getWsKey() {
        return wsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Ws_Key
     *
     * @param wsKey the value for Ifs_key.Ws_Key
     *
     * @mbggenerated
     */
    public void setWsKey(String wsKey) {
        this.wsKey = wsKey == null ? null : wsKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Ifs_Cd
     *
     * @return the value of Ifs_key.Ifs_Cd
     *
     * @mbggenerated
     */
    public String getIfsCd() {
        return ifsCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Ifs_Cd
     *
     * @param ifsCd the value for Ifs_key.Ifs_Cd
     *
     * @mbggenerated
     */
    public void setIfsCd(String ifsCd) {
        this.ifsCd = ifsCd == null ? null : ifsCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Ws_Type
     *
     * @return the value of Ifs_key.Ws_Type
     *
     * @mbggenerated
     */
    public String getWsType() {
        return wsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Ws_Type
     *
     * @param wsType the value for Ifs_key.Ws_Type
     *
     * @mbggenerated
     */
    public void setWsType(String wsType) {
        this.wsType = wsType == null ? null : wsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Create_Time
     *
     * @return the value of Ifs_key.Create_Time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Create_Time
     *
     * @param createTime the value for Ifs_key.Create_Time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Invalid_Time
     *
     * @return the value of Ifs_key.Invalid_Time
     *
     * @mbggenerated
     */
    public Date getInvalidTime() {
        return invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Invalid_Time
     *
     * @param invalidTime the value for Ifs_key.Invalid_Time
     *
     * @mbggenerated
     */
    public void setInvalidTime(Date invalidTime) {
        this.invalidTime = invalidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_key.Status
     *
     * @return the value of Ifs_key.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_key.Status
     *
     * @param status the value for Ifs_key.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}