package com.ami.ec.channel.domain.officialPlugin;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SkuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sku
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sku
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sku
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public SkuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Sku
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("Sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("Sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Integer value) {
            addCriterion("Sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Integer value) {
            addCriterion("Sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Integer value) {
            addCriterion("Sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Integer value) {
            addCriterion("Sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("Sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Integer> values) {
            addCriterion("Sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Integer> values) {
            addCriterion("Sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("Sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andItemCdIsNull() {
            addCriterion("Item_cd is null");
            return (Criteria) this;
        }

        public Criteria andItemCdIsNotNull() {
            addCriterion("Item_cd is not null");
            return (Criteria) this;
        }

        public Criteria andItemCdEqualTo(String value) {
            addCriterion("Item_cd =", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotEqualTo(String value) {
            addCriterion("Item_cd <>", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdGreaterThan(String value) {
            addCriterion("Item_cd >", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdGreaterThanOrEqualTo(String value) {
            addCriterion("Item_cd >=", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLessThan(String value) {
            addCriterion("Item_cd <", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLessThanOrEqualTo(String value) {
            addCriterion("Item_cd <=", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdLike(String value) {
            addCriterion("Item_cd like", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotLike(String value) {
            addCriterion("Item_cd not like", value, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdIn(List<String> values) {
            addCriterion("Item_cd in", values, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotIn(List<String> values) {
            addCriterion("Item_cd not in", values, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdBetween(String value1, String value2) {
            addCriterion("Item_cd between", value1, value2, "itemCd");
            return (Criteria) this;
        }

        public Criteria andItemCdNotBetween(String value1, String value2) {
            addCriterion("Item_cd not between", value1, value2, "itemCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNull() {
            addCriterion("Sku_cd is null");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNotNull() {
            addCriterion("Sku_cd is not null");
            return (Criteria) this;
        }

        public Criteria andSkuCdEqualTo(String value) {
            addCriterion("Sku_cd =", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotEqualTo(String value) {
            addCriterion("Sku_cd <>", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThan(String value) {
            addCriterion("Sku_cd >", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThanOrEqualTo(String value) {
            addCriterion("Sku_cd >=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThan(String value) {
            addCriterion("Sku_cd <", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThanOrEqualTo(String value) {
            addCriterion("Sku_cd <=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLike(String value) {
            addCriterion("Sku_cd like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotLike(String value) {
            addCriterion("Sku_cd not like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdIn(List<String> values) {
            addCriterion("Sku_cd in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotIn(List<String> values) {
            addCriterion("Sku_cd not in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdBetween(String value1, String value2) {
            addCriterion("Sku_cd between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotBetween(String value1, String value2) {
            addCriterion("Sku_cd not between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuProp1IsNull() {
            addCriterion("Sku_prop_1 is null");
            return (Criteria) this;
        }

        public Criteria andSkuProp1IsNotNull() {
            addCriterion("Sku_prop_1 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuProp1EqualTo(String value) {
            addCriterion("Sku_prop_1 =", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotEqualTo(String value) {
            addCriterion("Sku_prop_1 <>", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1GreaterThan(String value) {
            addCriterion("Sku_prop_1 >", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1GreaterThanOrEqualTo(String value) {
            addCriterion("Sku_prop_1 >=", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1LessThan(String value) {
            addCriterion("Sku_prop_1 <", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1LessThanOrEqualTo(String value) {
            addCriterion("Sku_prop_1 <=", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1Like(String value) {
            addCriterion("Sku_prop_1 like", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotLike(String value) {
            addCriterion("Sku_prop_1 not like", value, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1In(List<String> values) {
            addCriterion("Sku_prop_1 in", values, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotIn(List<String> values) {
            addCriterion("Sku_prop_1 not in", values, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1Between(String value1, String value2) {
            addCriterion("Sku_prop_1 between", value1, value2, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp1NotBetween(String value1, String value2) {
            addCriterion("Sku_prop_1 not between", value1, value2, "skuProp1");
            return (Criteria) this;
        }

        public Criteria andSkuProp2IsNull() {
            addCriterion("Sku_prop_2 is null");
            return (Criteria) this;
        }

        public Criteria andSkuProp2IsNotNull() {
            addCriterion("Sku_prop_2 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuProp2EqualTo(String value) {
            addCriterion("Sku_prop_2 =", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotEqualTo(String value) {
            addCriterion("Sku_prop_2 <>", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2GreaterThan(String value) {
            addCriterion("Sku_prop_2 >", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2GreaterThanOrEqualTo(String value) {
            addCriterion("Sku_prop_2 >=", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2LessThan(String value) {
            addCriterion("Sku_prop_2 <", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2LessThanOrEqualTo(String value) {
            addCriterion("Sku_prop_2 <=", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2Like(String value) {
            addCriterion("Sku_prop_2 like", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotLike(String value) {
            addCriterion("Sku_prop_2 not like", value, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2In(List<String> values) {
            addCriterion("Sku_prop_2 in", values, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotIn(List<String> values) {
            addCriterion("Sku_prop_2 not in", values, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2Between(String value1, String value2) {
            addCriterion("Sku_prop_2 between", value1, value2, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp2NotBetween(String value1, String value2) {
            addCriterion("Sku_prop_2 not between", value1, value2, "skuProp2");
            return (Criteria) this;
        }

        public Criteria andSkuProp3IsNull() {
            addCriterion("Sku_prop_3 is null");
            return (Criteria) this;
        }

        public Criteria andSkuProp3IsNotNull() {
            addCriterion("Sku_prop_3 is not null");
            return (Criteria) this;
        }

        public Criteria andSkuProp3EqualTo(String value) {
            addCriterion("Sku_prop_3 =", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotEqualTo(String value) {
            addCriterion("Sku_prop_3 <>", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3GreaterThan(String value) {
            addCriterion("Sku_prop_3 >", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3GreaterThanOrEqualTo(String value) {
            addCriterion("Sku_prop_3 >=", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3LessThan(String value) {
            addCriterion("Sku_prop_3 <", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3LessThanOrEqualTo(String value) {
            addCriterion("Sku_prop_3 <=", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3Like(String value) {
            addCriterion("Sku_prop_3 like", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotLike(String value) {
            addCriterion("Sku_prop_3 not like", value, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3In(List<String> values) {
            addCriterion("Sku_prop_3 in", values, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotIn(List<String> values) {
            addCriterion("Sku_prop_3 not in", values, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3Between(String value1, String value2) {
            addCriterion("Sku_prop_3 between", value1, value2, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andSkuProp3NotBetween(String value1, String value2) {
            addCriterion("Sku_prop_3 not between", value1, value2, "skuProp3");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("Stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("Stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(Integer value) {
            addCriterion("Stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(Integer value) {
            addCriterion("Stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(Integer value) {
            addCriterion("Stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("Stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(Integer value) {
            addCriterion("Stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(Integer value) {
            addCriterion("Stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<Integer> values) {
            addCriterion("Stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<Integer> values) {
            addCriterion("Stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(Integer value1, Integer value2) {
            addCriterion("Stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(Integer value1, Integer value2) {
            addCriterion("Stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNull() {
            addCriterion("Reserve1 is null");
            return (Criteria) this;
        }

        public Criteria andReserve1IsNotNull() {
            addCriterion("Reserve1 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve1EqualTo(String value) {
            addCriterion("Reserve1 =", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotEqualTo(String value) {
            addCriterion("Reserve1 <>", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThan(String value) {
            addCriterion("Reserve1 >", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1GreaterThanOrEqualTo(String value) {
            addCriterion("Reserve1 >=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThan(String value) {
            addCriterion("Reserve1 <", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1LessThanOrEqualTo(String value) {
            addCriterion("Reserve1 <=", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Like(String value) {
            addCriterion("Reserve1 like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotLike(String value) {
            addCriterion("Reserve1 not like", value, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1In(List<String> values) {
            addCriterion("Reserve1 in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotIn(List<String> values) {
            addCriterion("Reserve1 not in", values, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1Between(String value1, String value2) {
            addCriterion("Reserve1 between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve1NotBetween(String value1, String value2) {
            addCriterion("Reserve1 not between", value1, value2, "reserve1");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNull() {
            addCriterion("Reserve2 is null");
            return (Criteria) this;
        }

        public Criteria andReserve2IsNotNull() {
            addCriterion("Reserve2 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve2EqualTo(String value) {
            addCriterion("Reserve2 =", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotEqualTo(String value) {
            addCriterion("Reserve2 <>", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThan(String value) {
            addCriterion("Reserve2 >", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2GreaterThanOrEqualTo(String value) {
            addCriterion("Reserve2 >=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThan(String value) {
            addCriterion("Reserve2 <", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2LessThanOrEqualTo(String value) {
            addCriterion("Reserve2 <=", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Like(String value) {
            addCriterion("Reserve2 like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotLike(String value) {
            addCriterion("Reserve2 not like", value, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2In(List<String> values) {
            addCriterion("Reserve2 in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotIn(List<String> values) {
            addCriterion("Reserve2 not in", values, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2Between(String value1, String value2) {
            addCriterion("Reserve2 between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve2NotBetween(String value1, String value2) {
            addCriterion("Reserve2 not between", value1, value2, "reserve2");
            return (Criteria) this;
        }

        public Criteria andReserve3IsNull() {
            addCriterion("Reserve3 is null");
            return (Criteria) this;
        }

        public Criteria andReserve3IsNotNull() {
            addCriterion("Reserve3 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve3EqualTo(String value) {
            addCriterion("Reserve3 =", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotEqualTo(String value) {
            addCriterion("Reserve3 <>", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3GreaterThan(String value) {
            addCriterion("Reserve3 >", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3GreaterThanOrEqualTo(String value) {
            addCriterion("Reserve3 >=", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3LessThan(String value) {
            addCriterion("Reserve3 <", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3LessThanOrEqualTo(String value) {
            addCriterion("Reserve3 <=", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3Like(String value) {
            addCriterion("Reserve3 like", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotLike(String value) {
            addCriterion("Reserve3 not like", value, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3In(List<String> values) {
            addCriterion("Reserve3 in", values, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotIn(List<String> values) {
            addCriterion("Reserve3 not in", values, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3Between(String value1, String value2) {
            addCriterion("Reserve3 between", value1, value2, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve3NotBetween(String value1, String value2) {
            addCriterion("Reserve3 not between", value1, value2, "reserve3");
            return (Criteria) this;
        }

        public Criteria andReserve4IsNull() {
            addCriterion("Reserve4 is null");
            return (Criteria) this;
        }

        public Criteria andReserve4IsNotNull() {
            addCriterion("Reserve4 is not null");
            return (Criteria) this;
        }

        public Criteria andReserve4EqualTo(String value) {
            addCriterion("Reserve4 =", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotEqualTo(String value) {
            addCriterion("Reserve4 <>", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4GreaterThan(String value) {
            addCriterion("Reserve4 >", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4GreaterThanOrEqualTo(String value) {
            addCriterion("Reserve4 >=", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4LessThan(String value) {
            addCriterion("Reserve4 <", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4LessThanOrEqualTo(String value) {
            addCriterion("Reserve4 <=", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4Like(String value) {
            addCriterion("Reserve4 like", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotLike(String value) {
            addCriterion("Reserve4 not like", value, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4In(List<String> values) {
            addCriterion("Reserve4 in", values, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotIn(List<String> values) {
            addCriterion("Reserve4 not in", values, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4Between(String value1, String value2) {
            addCriterion("Reserve4 between", value1, value2, "reserve4");
            return (Criteria) this;
        }

        public Criteria andReserve4NotBetween(String value1, String value2) {
            addCriterion("Reserve4 not between", value1, value2, "reserve4");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeIsNull() {
            addCriterion("Price_update_time is null");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeIsNotNull() {
            addCriterion("Price_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeEqualTo(Date value) {
            addCriterion("Price_update_time =", value, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeNotEqualTo(Date value) {
            addCriterion("Price_update_time <>", value, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeGreaterThan(Date value) {
            addCriterion("Price_update_time >", value, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Price_update_time >=", value, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeLessThan(Date value) {
            addCriterion("Price_update_time <", value, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Price_update_time <=", value, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeIn(List<Date> values) {
            addCriterion("Price_update_time in", values, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeNotIn(List<Date> values) {
            addCriterion("Price_update_time not in", values, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("Price_update_time between", value1, value2, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPriceUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Price_update_time not between", value1, value2, "priceUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeIsNull() {
            addCriterion("Stock_update_time is null");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeIsNotNull() {
            addCriterion("Stock_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeEqualTo(Date value) {
            addCriterion("Stock_update_time =", value, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeNotEqualTo(Date value) {
            addCriterion("Stock_update_time <>", value, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeGreaterThan(Date value) {
            addCriterion("Stock_update_time >", value, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Stock_update_time >=", value, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeLessThan(Date value) {
            addCriterion("Stock_update_time <", value, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Stock_update_time <=", value, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeIn(List<Date> values) {
            addCriterion("Stock_update_time in", values, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeNotIn(List<Date> values) {
            addCriterion("Stock_update_time not in", values, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("Stock_update_time between", value1, value2, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStockUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Stock_update_time not between", value1, value2, "stockUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("Last_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("Last_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("Last_modify_time =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("Last_modify_time <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("Last_modify_time >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Last_modify_time >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("Last_modify_time <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("Last_modify_time <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("Last_modify_time in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("Last_modify_time not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("Last_modify_time between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("Last_modify_time not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("Create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("Create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("Create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("Create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("Create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("Create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("Create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("Create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("Create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andPriceFlagIsNull() {
            addCriterion("Price_flag is null");
            return (Criteria) this;
        }

        public Criteria andPriceFlagIsNotNull() {
            addCriterion("Price_flag is not null");
            return (Criteria) this;
        }

        public Criteria andPriceFlagEqualTo(Integer value) {
            addCriterion("Price_flag =", value, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagNotEqualTo(Integer value) {
            addCriterion("Price_flag <>", value, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagGreaterThan(Integer value) {
            addCriterion("Price_flag >", value, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("Price_flag >=", value, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagLessThan(Integer value) {
            addCriterion("Price_flag <", value, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagLessThanOrEqualTo(Integer value) {
            addCriterion("Price_flag <=", value, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagIn(List<Integer> values) {
            addCriterion("Price_flag in", values, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagNotIn(List<Integer> values) {
            addCriterion("Price_flag not in", values, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagBetween(Integer value1, Integer value2) {
            addCriterion("Price_flag between", value1, value2, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andPriceFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("Price_flag not between", value1, value2, "priceFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagIsNull() {
            addCriterion("Stock_flag is null");
            return (Criteria) this;
        }

        public Criteria andStockFlagIsNotNull() {
            addCriterion("Stock_flag is not null");
            return (Criteria) this;
        }

        public Criteria andStockFlagEqualTo(Integer value) {
            addCriterion("Stock_flag =", value, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagNotEqualTo(Integer value) {
            addCriterion("Stock_flag <>", value, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagGreaterThan(Integer value) {
            addCriterion("Stock_flag >", value, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("Stock_flag >=", value, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagLessThan(Integer value) {
            addCriterion("Stock_flag <", value, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagLessThanOrEqualTo(Integer value) {
            addCriterion("Stock_flag <=", value, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagIn(List<Integer> values) {
            addCriterion("Stock_flag in", values, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagNotIn(List<Integer> values) {
            addCriterion("Stock_flag not in", values, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagBetween(Integer value1, Integer value2) {
            addCriterion("Stock_flag between", value1, value2, "stockFlag");
            return (Criteria) this;
        }

        public Criteria andStockFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("Stock_flag not between", value1, value2, "stockFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Sku
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Sku
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}