package com.ami.ec.channel.dao.pluginManager;

import com.ami.ec.channel.domain.pluginManager.TaskDefine;
import com.ami.ec.channel.domain.pluginManager.TaskDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int countByExample(TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int deleteByExample(TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int insert(TaskDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int insertSelective(TaskDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    List<TaskDefine> selectByExample(TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    TaskDefine selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TaskDefine record, @Param("example") TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TaskDefine record, @Param("example") TaskDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Task_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskDefine record);
}