package com.ami.ec.channel.dao.asp;

import com.ami.ec.channel.domain.asp.AspIfsIDnIfLine;
import com.ami.ec.channel.domain.asp.AspIfsIDnIfLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AspIfsIDnIfLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    int countByExample(AspIfsIDnIfLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    int deleteByExample(AspIfsIDnIfLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    int insert(AspIfsIDnIfLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    int insertSelective(AspIfsIDnIfLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    List<AspIfsIDnIfLine> selectByExample(AspIfsIDnIfLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AspIfsIDnIfLine record, @Param("example") AspIfsIDnIfLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_i_dn_if_line
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AspIfsIDnIfLine record, @Param("example") AspIfsIDnIfLineExample example);
}