package com.ami.ifs.dao;

import com.ami.ifs.dao.IDnIfHead;
import com.ami.ifs.dao.IDnIfHeadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IDnIfHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    int countByExample(IDnIfHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    int deleteByExample(IDnIfHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    int insert(IDnIfHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    int insertSelective(IDnIfHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    List<IDnIfHead> selectByExample(IDnIfHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IDnIfHead record, @Param("example") IDnIfHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_dn_if_head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IDnIfHead record, @Param("example") IDnIfHeadExample example);
}