package com.ami.ifs.dao;

import com.ami.ifs.dao.IfsType;
import com.ami.ifs.dao.IfsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IfsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    int countByExample(IfsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    int deleteByExample(IfsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    int insert(IfsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    int insertSelective(IfsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    List<IfsType> selectByExample(IfsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IfsType record, @Param("example") IfsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Ifs_Type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IfsType record, @Param("example") IfsTypeExample example);
}