package com.ami.ifs.dao;

import java.util.Date;

import org.apache.cxf.aegis.type.java5.XmlType;

@javax.xml.bind.annotation.XmlType(name="IfsUnit")
public class IfsUnit { 
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Store_Id
     *
     * @mbggenerated
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Store_Cd
     *
     * @mbggenerated
     */
    private String storeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Store_Name
     *
     * @mbggenerated
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Ifs_A_Cd
     *
     * @mbggenerated
     */
    private String ifsACd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Ifs_C_Cd
     *
     * @mbggenerated
     */
    private String ifsCCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Ws_A_Key
     *
     * @mbggenerated
     */
    private String wsAKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Operate_Time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_Unit.Ws_C_Key
     *
     * @mbggenerated
     */
    private String wsCKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Store_Id
     *
     * @return the value of Ifs_Unit.Store_Id
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Store_Id
     *
     * @param storeId the value for Ifs_Unit.Store_Id
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Store_Cd
     *
     * @return the value of Ifs_Unit.Store_Cd
     *
     * @mbggenerated
     */
    public String getStoreCd() {
        return storeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Store_Cd
     *
     * @param storeCd the value for Ifs_Unit.Store_Cd
     *
     * @mbggenerated
     */
    public void setStoreCd(String storeCd) {
        this.storeCd = storeCd == null ? null : storeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Store_Name
     *
     * @return the value of Ifs_Unit.Store_Name
     *
     * @mbggenerated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Store_Name
     *
     * @param storeName the value for Ifs_Unit.Store_Name
     *
     * @mbggenerated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Ifs_A_Cd
     *
     * @return the value of Ifs_Unit.Ifs_A_Cd
     *
     * @mbggenerated
     */
    public String getIfsACd() {
        return ifsACd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Ifs_A_Cd
     *
     * @param ifsACd the value for Ifs_Unit.Ifs_A_Cd
     *
     * @mbggenerated
     */
    public void setIfsACd(String ifsACd) {
        this.ifsACd = ifsACd == null ? null : ifsACd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Ifs_C_Cd
     *
     * @return the value of Ifs_Unit.Ifs_C_Cd
     *
     * @mbggenerated
     */
    public String getIfsCCd() {
        return ifsCCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Ifs_C_Cd
     *
     * @param ifsCCd the value for Ifs_Unit.Ifs_C_Cd
     *
     * @mbggenerated
     */
    public void setIfsCCd(String ifsCCd) {
        this.ifsCCd = ifsCCd == null ? null : ifsCCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Ws_A_Key
     *
     * @return the value of Ifs_Unit.Ws_A_Key
     *
     * @mbggenerated
     */
    public String getWsAKey() {
        return wsAKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Ws_A_Key
     *
     * @param wsAKey the value for Ifs_Unit.Ws_A_Key
     *
     * @mbggenerated
     */
    public void setWsAKey(String wsAKey) {
        this.wsAKey = wsAKey == null ? null : wsAKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Operate_Time
     *
     * @return the value of Ifs_Unit.Operate_Time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Operate_Time
     *
     * @param operateTime the value for Ifs_Unit.Operate_Time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_Unit.Ws_C_Key
     *
     * @return the value of Ifs_Unit.Ws_C_Key
     *
     * @mbggenerated
     */
    public String getWsCKey() {
        return wsCKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_Unit.Ws_C_Key
     *
     * @param wsCKey the value for Ifs_Unit.Ws_C_Key
     *
     * @mbggenerated
     */
    public void setWsCKey(String wsCKey) {
        this.wsCKey = wsCKey == null ? null : wsCKey.trim();
    }
}