package com.ami.ifs.dao;

import com.ami.ifs.dao.IOrderLine;
import com.ami.ifs.dao.IOrderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IOrderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int countByExample(IOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int deleteByExample(IOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int insert(IOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int insertSelective(IOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    List<IOrderLine> selectByExample(IOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    IOrderLine selectByPrimaryKey(String orderLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IOrderLine record, @Param("example") IOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IOrderLine record, @Param("example") IOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table I_Order_Line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IOrderLine record);
}