package com.ami.ifs.dao;

import com.ami.ifs.dao.OOrderHead;
import com.ami.ifs.dao.OOrderHeadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OOrderHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    int countByExample(OOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    int deleteByExample(OOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    int insert(OOrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    int insertSelective(OOrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    List<OOrderHead> selectByExample(OOrderHeadExample example);
    
    List<OOrderHead> selectOrderHeadAndOrderLineByExample(OOrderHeadExample example);
    List<String> selectOrderHeadIdByExample(OOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OOrderHead record, @Param("example") OOrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OOrderHead record, @Param("example") OOrderHeadExample example);
}