package com.ami.ifs.dao;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cxf.aegis.type.java5.XmlType;

@javax.xml.bind.annotation.XmlType(name="UnitSkuExpands")
public class UnitSkuExpands {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Store_Id
     *
     * @mbggenerated
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Operate_Type
     *
     * @mbggenerated
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Ifs_A_Cd
     *
     * @mbggenerated
     */
    private String ifsACd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Ifs_C_Cd
     *
     * @mbggenerated
     */
    private String ifsCCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Sku_Cd
     *
     * @mbggenerated
     */
    private String skuCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Item_Cd
     *
     * @mbggenerated
     */
    private String itemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Std_Price
     *
     * @mbggenerated
     */
    private BigDecimal stdPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Market_Price
     *
     * @mbggenerated
     */
    private BigDecimal marketPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Inv_Qty
     *
     * @mbggenerated
     */
    private BigDecimal invQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Sold_Qty
     *
     * @mbggenerated
     */
    private BigDecimal soldQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Operate_Time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Unit_Sku_Expands.Timestamp
     *
     * @mbggenerated
     */
    private Date timestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Id
     *
     * @return the value of Unit_Sku_Expands.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Id
     *
     * @param id the value for Unit_Sku_Expands.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Store_Id
     *
     * @return the value of Unit_Sku_Expands.Store_Id
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Store_Id
     *
     * @param storeId the value for Unit_Sku_Expands.Store_Id
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Operate_Type
     *
     * @return the value of Unit_Sku_Expands.Operate_Type
     *
     * @mbggenerated
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Operate_Type
     *
     * @param operateType the value for Unit_Sku_Expands.Operate_Type
     *
     * @mbggenerated
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Ifs_A_Cd
     *
     * @return the value of Unit_Sku_Expands.Ifs_A_Cd
     *
     * @mbggenerated
     */
    public String getIfsACd() {
        return ifsACd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Ifs_A_Cd
     *
     * @param ifsACd the value for Unit_Sku_Expands.Ifs_A_Cd
     *
     * @mbggenerated
     */
    public void setIfsACd(String ifsACd) {
        this.ifsACd = ifsACd == null ? null : ifsACd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Ifs_C_Cd
     *
     * @return the value of Unit_Sku_Expands.Ifs_C_Cd
     *
     * @mbggenerated
     */
    public String getIfsCCd() {
        return ifsCCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Ifs_C_Cd
     *
     * @param ifsCCd the value for Unit_Sku_Expands.Ifs_C_Cd
     *
     * @mbggenerated
     */
    public void setIfsCCd(String ifsCCd) {
        this.ifsCCd = ifsCCd == null ? null : ifsCCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Sku_Cd
     *
     * @return the value of Unit_Sku_Expands.Sku_Cd
     *
     * @mbggenerated
     */
    public String getSkuCd() {
        return skuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Sku_Cd
     *
     * @param skuCd the value for Unit_Sku_Expands.Sku_Cd
     *
     * @mbggenerated
     */
    public void setSkuCd(String skuCd) {
        this.skuCd = skuCd == null ? null : skuCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Item_Cd
     *
     * @return the value of Unit_Sku_Expands.Item_Cd
     *
     * @mbggenerated
     */
    public String getItemCd() {
        return itemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Item_Cd
     *
     * @param itemCd the value for Unit_Sku_Expands.Item_Cd
     *
     * @mbggenerated
     */
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd == null ? null : itemCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Std_Price
     *
     * @return the value of Unit_Sku_Expands.Std_Price
     *
     * @mbggenerated
     */
    public BigDecimal getStdPrice() {
        return stdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Std_Price
     *
     * @param stdPrice the value for Unit_Sku_Expands.Std_Price
     *
     * @mbggenerated
     */
    public void setStdPrice(BigDecimal stdPrice) {
        this.stdPrice = stdPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Market_Price
     *
     * @return the value of Unit_Sku_Expands.Market_Price
     *
     * @mbggenerated
     */
    public BigDecimal getMarketPrice() {
        return marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Market_Price
     *
     * @param marketPrice the value for Unit_Sku_Expands.Market_Price
     *
     * @mbggenerated
     */
    public void setMarketPrice(BigDecimal marketPrice) {
        this.marketPrice = marketPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Inv_Qty
     *
     * @return the value of Unit_Sku_Expands.Inv_Qty
     *
     * @mbggenerated
     */
    public BigDecimal getInvQty() {
        return invQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Inv_Qty
     *
     * @param invQty the value for Unit_Sku_Expands.Inv_Qty
     *
     * @mbggenerated
     */
    public void setInvQty(BigDecimal invQty) {
        this.invQty = invQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Sold_Qty
     *
     * @return the value of Unit_Sku_Expands.Sold_Qty
     *
     * @mbggenerated
     */
    public BigDecimal getSoldQty() {
        return soldQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Sold_Qty
     *
     * @param soldQty the value for Unit_Sku_Expands.Sold_Qty
     *
     * @mbggenerated
     */
    public void setSoldQty(BigDecimal soldQty) {
        this.soldQty = soldQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Operate_Time
     *
     * @return the value of Unit_Sku_Expands.Operate_Time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Operate_Time
     *
     * @param operateTime the value for Unit_Sku_Expands.Operate_Time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Unit_Sku_Expands.Timestamp
     *
     * @return the value of Unit_Sku_Expands.Timestamp
     *
     * @mbggenerated
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Unit_Sku_Expands.Timestamp
     *
     * @param timestamp the value for Unit_Sku_Expands.Timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
}