package com.ami.ifs.dao;

import com.ami.ifs.dao.ValueMapLine;
import com.ami.ifs.dao.ValueMapLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ValueMapLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int countByExample(ValueMapLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int deleteByExample(ValueMapLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long valueMapLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int insert(ValueMapLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int insertSelective(ValueMapLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    List<ValueMapLine> selectByExample(ValueMapLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    ValueMapLine selectByPrimaryKey(Long valueMapLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ValueMapLine record, @Param("example") ValueMapLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ValueMapLine record, @Param("example") ValueMapLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ValueMapLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Value_map_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ValueMapLine record);
}