package com.ami.ec.channel.domain.officialPlugin;

import java.math.BigDecimal;
import java.util.Date;

public class OrderLine {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Order_line_id
     *
     * @mbggenerated
     */
    private Integer orderLineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Order_no
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Order_line_no
     *
     * @mbggenerated
     */
    private String orderLineNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Line_index
     *
     * @mbggenerated
     */
    private Integer lineIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Item_cd
     *
     * @mbggenerated
     */
    private String itemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Sku_cd
     *
     * @mbggenerated
     */
    private String skuCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Sku_prop_1
     *
     * @mbggenerated
     */
    private String skuProp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Sku_prop_2
     *
     * @mbggenerated
     */
    private String skuProp2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Sku_prop_3
     *
     * @mbggenerated
     */
    private String skuProp3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Sale_price
     *
     * @mbggenerated
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.DiscountPrice
     *
     * @mbggenerated
     */
    private BigDecimal discountprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.DiscountPriceAmt
     *
     * @mbggenerated
     */
    private BigDecimal discountpriceamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.OrderPrice
     *
     * @mbggenerated
     */
    private BigDecimal orderprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.OrderPriceAmt
     *
     * @mbggenerated
     */
    private BigDecimal orderpriceamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.RealPrice
     *
     * @mbggenerated
     */
    private BigDecimal realprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.RealPriceAmt
     *
     * @mbggenerated
     */
    private BigDecimal realpriceamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.Order_line_status
     *
     * @mbggenerated
     */
    private String orderLineStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order_line.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Order_line_id
     *
     * @return the value of Order_line.Order_line_id
     *
     * @mbggenerated
     */
    public Integer getOrderLineId() {
        return orderLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Order_line_id
     *
     * @param orderLineId the value for Order_line.Order_line_id
     *
     * @mbggenerated
     */
    public void setOrderLineId(Integer orderLineId) {
        this.orderLineId = orderLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Order_no
     *
     * @return the value of Order_line.Order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Order_no
     *
     * @param orderNo the value for Order_line.Order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Order_line_no
     *
     * @return the value of Order_line.Order_line_no
     *
     * @mbggenerated
     */
    public String getOrderLineNo() {
        return orderLineNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Order_line_no
     *
     * @param orderLineNo the value for Order_line.Order_line_no
     *
     * @mbggenerated
     */
    public void setOrderLineNo(String orderLineNo) {
        this.orderLineNo = orderLineNo == null ? null : orderLineNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Line_index
     *
     * @return the value of Order_line.Line_index
     *
     * @mbggenerated
     */
    public Integer getLineIndex() {
        return lineIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Line_index
     *
     * @param lineIndex the value for Order_line.Line_index
     *
     * @mbggenerated
     */
    public void setLineIndex(Integer lineIndex) {
        this.lineIndex = lineIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Item_cd
     *
     * @return the value of Order_line.Item_cd
     *
     * @mbggenerated
     */
    public String getItemCd() {
        return itemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Item_cd
     *
     * @param itemCd the value for Order_line.Item_cd
     *
     * @mbggenerated
     */
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd == null ? null : itemCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Title
     *
     * @return the value of Order_line.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Title
     *
     * @param title the value for Order_line.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Sku_cd
     *
     * @return the value of Order_line.Sku_cd
     *
     * @mbggenerated
     */
    public String getSkuCd() {
        return skuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Sku_cd
     *
     * @param skuCd the value for Order_line.Sku_cd
     *
     * @mbggenerated
     */
    public void setSkuCd(String skuCd) {
        this.skuCd = skuCd == null ? null : skuCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Sku_prop_1
     *
     * @return the value of Order_line.Sku_prop_1
     *
     * @mbggenerated
     */
    public String getSkuProp1() {
        return skuProp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Sku_prop_1
     *
     * @param skuProp1 the value for Order_line.Sku_prop_1
     *
     * @mbggenerated
     */
    public void setSkuProp1(String skuProp1) {
        this.skuProp1 = skuProp1 == null ? null : skuProp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Sku_prop_2
     *
     * @return the value of Order_line.Sku_prop_2
     *
     * @mbggenerated
     */
    public String getSkuProp2() {
        return skuProp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Sku_prop_2
     *
     * @param skuProp2 the value for Order_line.Sku_prop_2
     *
     * @mbggenerated
     */
    public void setSkuProp2(String skuProp2) {
        this.skuProp2 = skuProp2 == null ? null : skuProp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Sku_prop_3
     *
     * @return the value of Order_line.Sku_prop_3
     *
     * @mbggenerated
     */
    public String getSkuProp3() {
        return skuProp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Sku_prop_3
     *
     * @param skuProp3 the value for Order_line.Sku_prop_3
     *
     * @mbggenerated
     */
    public void setSkuProp3(String skuProp3) {
        this.skuProp3 = skuProp3 == null ? null : skuProp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Num
     *
     * @return the value of Order_line.Num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Num
     *
     * @param num the value for Order_line.Num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Sale_price
     *
     * @return the value of Order_line.Sale_price
     *
     * @mbggenerated
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Sale_price
     *
     * @param salePrice the value for Order_line.Sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.DiscountPrice
     *
     * @return the value of Order_line.DiscountPrice
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountprice() {
        return discountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.DiscountPrice
     *
     * @param discountprice the value for Order_line.DiscountPrice
     *
     * @mbggenerated
     */
    public void setDiscountprice(BigDecimal discountprice) {
        this.discountprice = discountprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.DiscountPriceAmt
     *
     * @return the value of Order_line.DiscountPriceAmt
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountpriceamt() {
        return discountpriceamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.DiscountPriceAmt
     *
     * @param discountpriceamt the value for Order_line.DiscountPriceAmt
     *
     * @mbggenerated
     */
    public void setDiscountpriceamt(BigDecimal discountpriceamt) {
        this.discountpriceamt = discountpriceamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.OrderPrice
     *
     * @return the value of Order_line.OrderPrice
     *
     * @mbggenerated
     */
    public BigDecimal getOrderprice() {
        return orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.OrderPrice
     *
     * @param orderprice the value for Order_line.OrderPrice
     *
     * @mbggenerated
     */
    public void setOrderprice(BigDecimal orderprice) {
        this.orderprice = orderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.OrderPriceAmt
     *
     * @return the value of Order_line.OrderPriceAmt
     *
     * @mbggenerated
     */
    public BigDecimal getOrderpriceamt() {
        return orderpriceamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.OrderPriceAmt
     *
     * @param orderpriceamt the value for Order_line.OrderPriceAmt
     *
     * @mbggenerated
     */
    public void setOrderpriceamt(BigDecimal orderpriceamt) {
        this.orderpriceamt = orderpriceamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.RealPrice
     *
     * @return the value of Order_line.RealPrice
     *
     * @mbggenerated
     */
    public BigDecimal getRealprice() {
        return realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.RealPrice
     *
     * @param realprice the value for Order_line.RealPrice
     *
     * @mbggenerated
     */
    public void setRealprice(BigDecimal realprice) {
        this.realprice = realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.RealPriceAmt
     *
     * @return the value of Order_line.RealPriceAmt
     *
     * @mbggenerated
     */
    public BigDecimal getRealpriceamt() {
        return realpriceamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.RealPriceAmt
     *
     * @param realpriceamt the value for Order_line.RealPriceAmt
     *
     * @mbggenerated
     */
    public void setRealpriceamt(BigDecimal realpriceamt) {
        this.realpriceamt = realpriceamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Create_time
     *
     * @return the value of Order_line.Create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Create_time
     *
     * @param createTime the value for Order_line.Create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Last_modify_time
     *
     * @return the value of Order_line.Last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Last_modify_time
     *
     * @param lastModifyTime the value for Order_line.Last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.Order_line_status
     *
     * @return the value of Order_line.Order_line_status
     *
     * @mbggenerated
     */
    public String getOrderLineStatus() {
        return orderLineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.Order_line_status
     *
     * @param orderLineStatus the value for Order_line.Order_line_status
     *
     * @mbggenerated
     */
    public void setOrderLineStatus(String orderLineStatus) {
        this.orderLineStatus = orderLineStatus == null ? null : orderLineStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.ctime
     *
     * @return the value of Order_line.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.ctime
     *
     * @param ctime the value for Order_line.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order_line.mtime
     *
     * @return the value of Order_line.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order_line.mtime
     *
     * @param mtime the value for Order_line.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}