package com.ami.ec.channel.dao.pluginManager;

import com.ami.ec.channel.domain.pluginManager.IfDefineLine;
import com.ami.ec.channel.domain.pluginManager.IfDefineLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IfDefineLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int countByExample(IfDefineLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int deleteByExample(IfDefineLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ifLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int insert(IfDefineLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int insertSelective(IfDefineLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    List<IfDefineLine> selectByExample(IfDefineLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    IfDefineLine selectByPrimaryKey(Integer ifLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IfDefineLine record, @Param("example") IfDefineLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IfDefineLine record, @Param("example") IfDefineLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IfDefineLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table IF_define_line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IfDefineLine record);
}