package com.ami.ifs.dao;

import com.ami.ifs.dao.GlobalDefine;
import com.ami.ifs.dao.GlobalDefineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlobalDefineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int countByExample(GlobalDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int deleteByExample(GlobalDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int insert(GlobalDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int insertSelective(GlobalDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    List<GlobalDefine> selectByExample(GlobalDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    GlobalDefine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GlobalDefine record, @Param("example") GlobalDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GlobalDefine record, @Param("example") GlobalDefineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GlobalDefine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Global_define
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GlobalDefine record);
}