package com.ami.ec.channel.domain.pluginManager;

import java.util.Date;

public class BatLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_log.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_log.Bat_record_id
     *
     * @mbggenerated
     */
    private Long batRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_log.Log_time
     *
     * @mbggenerated
     */
    private Date logTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_log.Log_content
     *
     * @mbggenerated
     */
    private String logContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_log.Is_abnormal
     *
     * @mbggenerated
     */
    private Boolean isAbnormal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_log.ref_id
     *
     * @mbggenerated
     */
    private String refId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_log.Id
     *
     * @return the value of Bat_log.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_log.Id
     *
     * @param id the value for Bat_log.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_log.Bat_record_id
     *
     * @return the value of Bat_log.Bat_record_id
     *
     * @mbggenerated
     */
    public Long getBatRecordId() {
        return batRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_log.Bat_record_id
     *
     * @param batRecordId the value for Bat_log.Bat_record_id
     *
     * @mbggenerated
     */
    public void setBatRecordId(Long batRecordId) {
        this.batRecordId = batRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_log.Log_time
     *
     * @return the value of Bat_log.Log_time
     *
     * @mbggenerated
     */
    public Date getLogTime() {
        return logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_log.Log_time
     *
     * @param logTime the value for Bat_log.Log_time
     *
     * @mbggenerated
     */
    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_log.Log_content
     *
     * @return the value of Bat_log.Log_content
     *
     * @mbggenerated
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_log.Log_content
     *
     * @param logContent the value for Bat_log.Log_content
     *
     * @mbggenerated
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_log.Is_abnormal
     *
     * @return the value of Bat_log.Is_abnormal
     *
     * @mbggenerated
     */
    public Boolean getIsAbnormal() {
        return isAbnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_log.Is_abnormal
     *
     * @param isAbnormal the value for Bat_log.Is_abnormal
     *
     * @mbggenerated
     */
    public void setIsAbnormal(Boolean isAbnormal) {
        this.isAbnormal = isAbnormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_log.ref_id
     *
     * @return the value of Bat_log.ref_id
     *
     * @mbggenerated
     */
    public String getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_log.ref_id
     *
     * @param refId the value for Bat_log.ref_id
     *
     * @mbggenerated
     */
    public void setRefId(String refId) {
        this.refId = refId == null ? null : refId.trim();
    }
}