package com.ami.ec.channel.domain.pluginManager;

import java.util.Date;

public class BatRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Bat_record_id
     *
     * @mbggenerated
     */
    private Long batRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Bat_no
     *
     * @mbggenerated
     */
    private String batNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.End_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Parent_bat_id
     *
     * @mbggenerated
     */
    private Long parentBatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Src_data_num
     *
     * @mbggenerated
     */
    private Integer srcDataNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Real_data_num
     *
     * @mbggenerated
     */
    private Integer realDataNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Is_finished
     *
     * @mbggenerated
     */
    private Boolean isFinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Is_success
     *
     * @mbggenerated
     */
    private Boolean isSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Failed_reason
     *
     * @mbggenerated
     */
    private String failedReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Is_dealed
     *
     * @mbggenerated
     */
    private Boolean isDealed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Deal_remark
     *
     * @mbggenerated
     */
    private String dealRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.IF_id
     *
     * @mbggenerated
     */
    private Integer ifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Task_queue_id
     *
     * @mbggenerated
     */
    private Long taskQueueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Operate_user_id
     *
     * @mbggenerated
     */
    private Integer operateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Bat_record.Operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Bat_record_id
     *
     * @return the value of Bat_record.Bat_record_id
     *
     * @mbggenerated
     */
    public Long getBatRecordId() {
        return batRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Bat_record_id
     *
     * @param batRecordId the value for Bat_record.Bat_record_id
     *
     * @mbggenerated
     */
    public void setBatRecordId(Long batRecordId) {
        this.batRecordId = batRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Bat_no
     *
     * @return the value of Bat_record.Bat_no
     *
     * @mbggenerated
     */
    public String getBatNo() {
        return batNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Bat_no
     *
     * @param batNo the value for Bat_record.Bat_no
     *
     * @mbggenerated
     */
    public void setBatNo(String batNo) {
        this.batNo = batNo == null ? null : batNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Start_time
     *
     * @return the value of Bat_record.Start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Start_time
     *
     * @param startTime the value for Bat_record.Start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.End_time
     *
     * @return the value of Bat_record.End_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.End_time
     *
     * @param endTime the value for Bat_record.End_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Parent_bat_id
     *
     * @return the value of Bat_record.Parent_bat_id
     *
     * @mbggenerated
     */
    public Long getParentBatId() {
        return parentBatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Parent_bat_id
     *
     * @param parentBatId the value for Bat_record.Parent_bat_id
     *
     * @mbggenerated
     */
    public void setParentBatId(Long parentBatId) {
        this.parentBatId = parentBatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Src_data_num
     *
     * @return the value of Bat_record.Src_data_num
     *
     * @mbggenerated
     */
    public Integer getSrcDataNum() {
        return srcDataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Src_data_num
     *
     * @param srcDataNum the value for Bat_record.Src_data_num
     *
     * @mbggenerated
     */
    public void setSrcDataNum(Integer srcDataNum) {
        this.srcDataNum = srcDataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Real_data_num
     *
     * @return the value of Bat_record.Real_data_num
     *
     * @mbggenerated
     */
    public Integer getRealDataNum() {
        return realDataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Real_data_num
     *
     * @param realDataNum the value for Bat_record.Real_data_num
     *
     * @mbggenerated
     */
    public void setRealDataNum(Integer realDataNum) {
        this.realDataNum = realDataNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Is_finished
     *
     * @return the value of Bat_record.Is_finished
     *
     * @mbggenerated
     */
    public Boolean getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Is_finished
     *
     * @param isFinished the value for Bat_record.Is_finished
     *
     * @mbggenerated
     */
    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Is_success
     *
     * @return the value of Bat_record.Is_success
     *
     * @mbggenerated
     */
    public Boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Is_success
     *
     * @param isSuccess the value for Bat_record.Is_success
     *
     * @mbggenerated
     */
    public void setIsSuccess(Boolean isSuccess) {
        this.isSuccess = isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Failed_reason
     *
     * @return the value of Bat_record.Failed_reason
     *
     * @mbggenerated
     */
    public String getFailedReason() {
        return failedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Failed_reason
     *
     * @param failedReason the value for Bat_record.Failed_reason
     *
     * @mbggenerated
     */
    public void setFailedReason(String failedReason) {
        this.failedReason = failedReason == null ? null : failedReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Is_dealed
     *
     * @return the value of Bat_record.Is_dealed
     *
     * @mbggenerated
     */
    public Boolean getIsDealed() {
        return isDealed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Is_dealed
     *
     * @param isDealed the value for Bat_record.Is_dealed
     *
     * @mbggenerated
     */
    public void setIsDealed(Boolean isDealed) {
        this.isDealed = isDealed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Deal_remark
     *
     * @return the value of Bat_record.Deal_remark
     *
     * @mbggenerated
     */
    public String getDealRemark() {
        return dealRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Deal_remark
     *
     * @param dealRemark the value for Bat_record.Deal_remark
     *
     * @mbggenerated
     */
    public void setDealRemark(String dealRemark) {
        this.dealRemark = dealRemark == null ? null : dealRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.IF_id
     *
     * @return the value of Bat_record.IF_id
     *
     * @mbggenerated
     */
    public Integer getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.IF_id
     *
     * @param ifId the value for Bat_record.IF_id
     *
     * @mbggenerated
     */
    public void setIfId(Integer ifId) {
        this.ifId = ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Task_queue_id
     *
     * @return the value of Bat_record.Task_queue_id
     *
     * @mbggenerated
     */
    public Long getTaskQueueId() {
        return taskQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Task_queue_id
     *
     * @param taskQueueId the value for Bat_record.Task_queue_id
     *
     * @mbggenerated
     */
    public void setTaskQueueId(Long taskQueueId) {
        this.taskQueueId = taskQueueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Operate_user_id
     *
     * @return the value of Bat_record.Operate_user_id
     *
     * @mbggenerated
     */
    public Integer getOperateUserId() {
        return operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Operate_user_id
     *
     * @param operateUserId the value for Bat_record.Operate_user_id
     *
     * @mbggenerated
     */
    public void setOperateUserId(Integer operateUserId) {
        this.operateUserId = operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Bat_record.Operate_time
     *
     * @return the value of Bat_record.Operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Bat_record.Operate_time
     *
     * @param operateTime the value for Bat_record.Operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}