package com.ami.ifs.dao;

import com.ami.ifs.dao.OOrderLine;
import com.ami.ifs.dao.OOrderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OOrderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int countByExample(OOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int deleteByExample(OOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int insert(OOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int insertSelective(OOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    List<OOrderLine> selectByExample(OOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    OOrderLine selectByPrimaryKey(String orderLineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OOrderLine record, @Param("example") OOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OOrderLine record, @Param("example") OOrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OOrderLine record);
}