package com.ami.ec.channel.dao.officialPlugin;

import com.ami.ec.channel.domain.officialPlugin.OrderHead;
import com.ami.ec.channel.domain.officialPlugin.OrderHeadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int countByExample(OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int deleteByExample(OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer orderHeadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int insert(OrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int insertSelective(OrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    List<OrderHead> selectByExample(OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    OrderHead selectByPrimaryKey(Integer orderHeadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderHead record, @Param("example") OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderHead record, @Param("example") OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_head
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderHead record);
}