package com.ami.ifs.dao;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OOrderLineExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public OOrderLineExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderLineIdIsNull() {
            addCriterion("Order_Line_Id is null");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdIsNotNull() {
            addCriterion("Order_Line_Id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdEqualTo(String value) {
            addCriterion("Order_Line_Id =", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdNotEqualTo(String value) {
            addCriterion("Order_Line_Id <>", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdGreaterThan(String value) {
            addCriterion("Order_Line_Id >", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdGreaterThanOrEqualTo(String value) {
            addCriterion("Order_Line_Id >=", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdLessThan(String value) {
            addCriterion("Order_Line_Id <", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdLessThanOrEqualTo(String value) {
            addCriterion("Order_Line_Id <=", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdLike(String value) {
            addCriterion("Order_Line_Id like", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdNotLike(String value) {
            addCriterion("Order_Line_Id not like", value, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdIn(List<String> values) {
            addCriterion("Order_Line_Id in", values, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdNotIn(List<String> values) {
            addCriterion("Order_Line_Id not in", values, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdBetween(String value1, String value2) {
            addCriterion("Order_Line_Id between", value1, value2, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderLineIdNotBetween(String value1, String value2) {
            addCriterion("Order_Line_Id not between", value1, value2, "orderLineId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdIsNull() {
            addCriterion("Order_Head_Id is null");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdIsNotNull() {
            addCriterion("Order_Head_Id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdEqualTo(String value) {
            addCriterion("Order_Head_Id =", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotEqualTo(String value) {
            addCriterion("Order_Head_Id <>", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdGreaterThan(String value) {
            addCriterion("Order_Head_Id >", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdGreaterThanOrEqualTo(String value) {
            addCriterion("Order_Head_Id >=", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdLessThan(String value) {
            addCriterion("Order_Head_Id <", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdLessThanOrEqualTo(String value) {
            addCriterion("Order_Head_Id <=", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdLike(String value) {
            addCriterion("Order_Head_Id like", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotLike(String value) {
            addCriterion("Order_Head_Id not like", value, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdIn(List<String> values) {
            addCriterion("Order_Head_Id in", values, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotIn(List<String> values) {
            addCriterion("Order_Head_Id not in", values, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdBetween(String value1, String value2) {
            addCriterion("Order_Head_Id between", value1, value2, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOrderHeadIdNotBetween(String value1, String value2) {
            addCriterion("Order_Head_Id not between", value1, value2, "orderHeadId");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("Operate_Time is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("Operate_Time is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("Operate_Time =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("Operate_Time <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("Operate_Time >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Operate_Time >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("Operate_Time <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("Operate_Time <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("Operate_Time in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("Operate_Time not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("Operate_Time between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("Operate_Time not between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("Timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("Timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(Date value) {
            addCriterion("Timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(Date value) {
            addCriterion("Timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(Date value) {
            addCriterion("Timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("Timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(Date value) {
            addCriterion("Timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(Date value) {
            addCriterion("Timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<Date> values) {
            addCriterion("Timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<Date> values) {
            addCriterion("Timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(Date value1, Date value2) {
            addCriterion("Timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(Date value1, Date value2) {
            addCriterion("Timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoIsNull() {
            addCriterion("Orig_Order_Line_No is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoIsNotNull() {
            addCriterion("Orig_Order_Line_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoEqualTo(String value) {
            addCriterion("Orig_Order_Line_No =", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoNotEqualTo(String value) {
            addCriterion("Orig_Order_Line_No <>", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoGreaterThan(String value) {
            addCriterion("Orig_Order_Line_No >", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoGreaterThanOrEqualTo(String value) {
            addCriterion("Orig_Order_Line_No >=", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoLessThan(String value) {
            addCriterion("Orig_Order_Line_No <", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoLessThanOrEqualTo(String value) {
            addCriterion("Orig_Order_Line_No <=", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoLike(String value) {
            addCriterion("Orig_Order_Line_No like", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoNotLike(String value) {
            addCriterion("Orig_Order_Line_No not like", value, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoIn(List<String> values) {
            addCriterion("Orig_Order_Line_No in", values, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoNotIn(List<String> values) {
            addCriterion("Orig_Order_Line_No not in", values, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoBetween(String value1, String value2) {
            addCriterion("Orig_Order_Line_No between", value1, value2, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineNoNotBetween(String value1, String value2) {
            addCriterion("Orig_Order_Line_No not between", value1, value2, "origOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusIsNull() {
            addCriterion("Order_Line_Status is null");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusIsNotNull() {
            addCriterion("Order_Line_Status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusEqualTo(String value) {
            addCriterion("Order_Line_Status =", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusNotEqualTo(String value) {
            addCriterion("Order_Line_Status <>", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusGreaterThan(String value) {
            addCriterion("Order_Line_Status >", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Order_Line_Status >=", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusLessThan(String value) {
            addCriterion("Order_Line_Status <", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusLessThanOrEqualTo(String value) {
            addCriterion("Order_Line_Status <=", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusLike(String value) {
            addCriterion("Order_Line_Status like", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusNotLike(String value) {
            addCriterion("Order_Line_Status not like", value, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusIn(List<String> values) {
            addCriterion("Order_Line_Status in", values, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusNotIn(List<String> values) {
            addCriterion("Order_Line_Status not in", values, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusBetween(String value1, String value2) {
            addCriterion("Order_Line_Status between", value1, value2, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrderLineStatusNotBetween(String value1, String value2) {
            addCriterion("Order_Line_Status not between", value1, value2, "orderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusIsNull() {
            addCriterion("Orig_Order_Line_Status is null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusIsNotNull() {
            addCriterion("Orig_Order_Line_Status is not null");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusEqualTo(String value) {
            addCriterion("Orig_Order_Line_Status =", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusNotEqualTo(String value) {
            addCriterion("Orig_Order_Line_Status <>", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusGreaterThan(String value) {
            addCriterion("Orig_Order_Line_Status >", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Orig_Order_Line_Status >=", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusLessThan(String value) {
            addCriterion("Orig_Order_Line_Status <", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusLessThanOrEqualTo(String value) {
            addCriterion("Orig_Order_Line_Status <=", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusLike(String value) {
            addCriterion("Orig_Order_Line_Status like", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusNotLike(String value) {
            addCriterion("Orig_Order_Line_Status not like", value, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusIn(List<String> values) {
            addCriterion("Orig_Order_Line_Status in", values, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusNotIn(List<String> values) {
            addCriterion("Orig_Order_Line_Status not in", values, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusBetween(String value1, String value2) {
            addCriterion("Orig_Order_Line_Status between", value1, value2, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigOrderLineStatusNotBetween(String value1, String value2) {
            addCriterion("Orig_Order_Line_Status not between", value1, value2, "origOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdIsNull() {
            addCriterion("Orig_Sku_Id is null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdIsNotNull() {
            addCriterion("Orig_Sku_Id is not null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdEqualTo(String value) {
            addCriterion("Orig_Sku_Id =", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotEqualTo(String value) {
            addCriterion("Orig_Sku_Id <>", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdGreaterThan(String value) {
            addCriterion("Orig_Sku_Id >", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdGreaterThanOrEqualTo(String value) {
            addCriterion("Orig_Sku_Id >=", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdLessThan(String value) {
            addCriterion("Orig_Sku_Id <", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdLessThanOrEqualTo(String value) {
            addCriterion("Orig_Sku_Id <=", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdLike(String value) {
            addCriterion("Orig_Sku_Id like", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotLike(String value) {
            addCriterion("Orig_Sku_Id not like", value, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdIn(List<String> values) {
            addCriterion("Orig_Sku_Id in", values, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotIn(List<String> values) {
            addCriterion("Orig_Sku_Id not in", values, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdBetween(String value1, String value2) {
            addCriterion("Orig_Sku_Id between", value1, value2, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andOrigSkuIdNotBetween(String value1, String value2) {
            addCriterion("Orig_Sku_Id not between", value1, value2, "origSkuId");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNull() {
            addCriterion("Sku_Cd is null");
            return (Criteria) this;
        }

        public Criteria andSkuCdIsNotNull() {
            addCriterion("Sku_Cd is not null");
            return (Criteria) this;
        }

        public Criteria andSkuCdEqualTo(String value) {
            addCriterion("Sku_Cd =", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotEqualTo(String value) {
            addCriterion("Sku_Cd <>", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThan(String value) {
            addCriterion("Sku_Cd >", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdGreaterThanOrEqualTo(String value) {
            addCriterion("Sku_Cd >=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThan(String value) {
            addCriterion("Sku_Cd <", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLessThanOrEqualTo(String value) {
            addCriterion("Sku_Cd <=", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdLike(String value) {
            addCriterion("Sku_Cd like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotLike(String value) {
            addCriterion("Sku_Cd not like", value, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdIn(List<String> values) {
            addCriterion("Sku_Cd in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotIn(List<String> values) {
            addCriterion("Sku_Cd not in", values, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdBetween(String value1, String value2) {
            addCriterion("Sku_Cd between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuCdNotBetween(String value1, String value2) {
            addCriterion("Sku_Cd not between", value1, value2, "skuCd");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("Sku_Name is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("Sku_Name is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("Sku_Name =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("Sku_Name <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("Sku_Name >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("Sku_Name >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("Sku_Name <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("Sku_Name <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("Sku_Name like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("Sku_Name not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("Sku_Name in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("Sku_Name not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("Sku_Name between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("Sku_Name not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andQtyIsNull() {
            addCriterion("Qty is null");
            return (Criteria) this;
        }

        public Criteria andQtyIsNotNull() {
            addCriterion("Qty is not null");
            return (Criteria) this;
        }

        public Criteria andQtyEqualTo(Long value) {
            addCriterion("Qty =", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotEqualTo(Long value) {
            addCriterion("Qty <>", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThan(Long value) {
            addCriterion("Qty >", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyGreaterThanOrEqualTo(Long value) {
            addCriterion("Qty >=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThan(Long value) {
            addCriterion("Qty <", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyLessThanOrEqualTo(Long value) {
            addCriterion("Qty <=", value, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyIn(List<Long> values) {
            addCriterion("Qty in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotIn(List<Long> values) {
            addCriterion("Qty not in", values, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyBetween(Long value1, Long value2) {
            addCriterion("Qty between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andQtyNotBetween(Long value1, Long value2) {
            addCriterion("Qty not between", value1, value2, "qty");
            return (Criteria) this;
        }

        public Criteria andStdPriceIsNull() {
            addCriterion("Std_Price is null");
            return (Criteria) this;
        }

        public Criteria andStdPriceIsNotNull() {
            addCriterion("Std_Price is not null");
            return (Criteria) this;
        }

        public Criteria andStdPriceEqualTo(BigDecimal value) {
            addCriterion("Std_Price =", value, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceNotEqualTo(BigDecimal value) {
            addCriterion("Std_Price <>", value, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceGreaterThan(BigDecimal value) {
            addCriterion("Std_Price >", value, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Std_Price >=", value, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceLessThan(BigDecimal value) {
            addCriterion("Std_Price <", value, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Std_Price <=", value, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceIn(List<BigDecimal> values) {
            addCriterion("Std_Price in", values, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceNotIn(List<BigDecimal> values) {
            addCriterion("Std_Price not in", values, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Std_Price between", value1, value2, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andStdPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Std_Price not between", value1, value2, "stdPrice");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeIsNull() {
            addCriterion("Adjust_Fee is null");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeIsNotNull() {
            addCriterion("Adjust_Fee is not null");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeEqualTo(BigDecimal value) {
            addCriterion("Adjust_Fee =", value, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeNotEqualTo(BigDecimal value) {
            addCriterion("Adjust_Fee <>", value, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeGreaterThan(BigDecimal value) {
            addCriterion("Adjust_Fee >", value, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Adjust_Fee >=", value, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeLessThan(BigDecimal value) {
            addCriterion("Adjust_Fee <", value, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Adjust_Fee <=", value, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeIn(List<BigDecimal> values) {
            addCriterion("Adjust_Fee in", values, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeNotIn(List<BigDecimal> values) {
            addCriterion("Adjust_Fee not in", values, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Adjust_Fee between", value1, value2, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andAdjustFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Adjust_Fee not between", value1, value2, "adjustFee");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andStdAmtIsNull() {
            addCriterion("Std_Amt is null");
            return (Criteria) this;
        }

        public Criteria andStdAmtIsNotNull() {
            addCriterion("Std_Amt is not null");
            return (Criteria) this;
        }

        public Criteria andStdAmtEqualTo(BigDecimal value) {
            addCriterion("Std_Amt =", value, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtNotEqualTo(BigDecimal value) {
            addCriterion("Std_Amt <>", value, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtGreaterThan(BigDecimal value) {
            addCriterion("Std_Amt >", value, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Std_Amt >=", value, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtLessThan(BigDecimal value) {
            addCriterion("Std_Amt <", value, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Std_Amt <=", value, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtIn(List<BigDecimal> values) {
            addCriterion("Std_Amt in", values, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtNotIn(List<BigDecimal> values) {
            addCriterion("Std_Amt not in", values, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Std_Amt between", value1, value2, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andStdAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Std_Amt not between", value1, value2, "stdAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtIsNull() {
            addCriterion("Total_Amt is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmtIsNotNull() {
            addCriterion("Total_Amt is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmtEqualTo(BigDecimal value) {
            addCriterion("Total_Amt =", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtNotEqualTo(BigDecimal value) {
            addCriterion("Total_Amt <>", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtGreaterThan(BigDecimal value) {
            addCriterion("Total_Amt >", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Amt >=", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtLessThan(BigDecimal value) {
            addCriterion("Total_Amt <", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Total_Amt <=", value, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtIn(List<BigDecimal> values) {
            addCriterion("Total_Amt in", values, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtNotIn(List<BigDecimal> values) {
            addCriterion("Total_Amt not in", values, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Amt between", value1, value2, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andTotalAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Total_Amt not between", value1, value2, "totalAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeIsNull() {
            addCriterion("Discount_Fee is null");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeIsNotNull() {
            addCriterion("Discount_Fee is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeEqualTo(BigDecimal value) {
            addCriterion("Discount_Fee =", value, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeNotEqualTo(BigDecimal value) {
            addCriterion("Discount_Fee <>", value, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeGreaterThan(BigDecimal value) {
            addCriterion("Discount_Fee >", value, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Discount_Fee >=", value, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeLessThan(BigDecimal value) {
            addCriterion("Discount_Fee <", value, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Discount_Fee <=", value, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeIn(List<BigDecimal> values) {
            addCriterion("Discount_Fee in", values, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeNotIn(List<BigDecimal> values) {
            addCriterion("Discount_Fee not in", values, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Discount_Fee between", value1, value2, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Discount_Fee not between", value1, value2, "discountFee");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtIsNull() {
            addCriterion("Discount_Amt is null");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtIsNotNull() {
            addCriterion("Discount_Amt is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtEqualTo(BigDecimal value) {
            addCriterion("Discount_Amt =", value, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtNotEqualTo(BigDecimal value) {
            addCriterion("Discount_Amt <>", value, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtGreaterThan(BigDecimal value) {
            addCriterion("Discount_Amt >", value, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Discount_Amt >=", value, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtLessThan(BigDecimal value) {
            addCriterion("Discount_Amt <", value, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Discount_Amt <=", value, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtIn(List<BigDecimal> values) {
            addCriterion("Discount_Amt in", values, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtNotIn(List<BigDecimal> values) {
            addCriterion("Discount_Amt not in", values, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Discount_Amt between", value1, value2, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andDiscountAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Discount_Amt not between", value1, value2, "discountAmt");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andDispIndexIsNull() {
            addCriterion("Disp_Index is null");
            return (Criteria) this;
        }

        public Criteria andDispIndexIsNotNull() {
            addCriterion("Disp_Index is not null");
            return (Criteria) this;
        }

        public Criteria andDispIndexEqualTo(Integer value) {
            addCriterion("Disp_Index =", value, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexNotEqualTo(Integer value) {
            addCriterion("Disp_Index <>", value, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexGreaterThan(Integer value) {
            addCriterion("Disp_Index >", value, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Disp_Index >=", value, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexLessThan(Integer value) {
            addCriterion("Disp_Index <", value, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexLessThanOrEqualTo(Integer value) {
            addCriterion("Disp_Index <=", value, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexIn(List<Integer> values) {
            addCriterion("Disp_Index in", values, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexNotIn(List<Integer> values) {
            addCriterion("Disp_Index not in", values, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexBetween(Integer value1, Integer value2) {
            addCriterion("Disp_Index between", value1, value2, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andDispIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("Disp_Index not between", value1, value2, "dispIndex");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoIsNull() {
            addCriterion("Orig_Ref_Order_Line_No is null");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoIsNotNull() {
            addCriterion("Orig_Ref_Order_Line_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_No =", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoNotEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_No <>", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoGreaterThan(String value) {
            addCriterion("Orig_Ref_Order_Line_No >", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoGreaterThanOrEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_No >=", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoLessThan(String value) {
            addCriterion("Orig_Ref_Order_Line_No <", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoLessThanOrEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_No <=", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoLike(String value) {
            addCriterion("Orig_Ref_Order_Line_No like", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoNotLike(String value) {
            addCriterion("Orig_Ref_Order_Line_No not like", value, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoIn(List<String> values) {
            addCriterion("Orig_Ref_Order_Line_No in", values, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoNotIn(List<String> values) {
            addCriterion("Orig_Ref_Order_Line_No not in", values, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoBetween(String value1, String value2) {
            addCriterion("Orig_Ref_Order_Line_No between", value1, value2, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineNoNotBetween(String value1, String value2) {
            addCriterion("Orig_Ref_Order_Line_No not between", value1, value2, "origRefOrderLineNo");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusIsNull() {
            addCriterion("Orig_Ref_Order_Line_Status is null");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusIsNotNull() {
            addCriterion("Orig_Ref_Order_Line_Status is not null");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_Status =", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusNotEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_Status <>", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusGreaterThan(String value) {
            addCriterion("Orig_Ref_Order_Line_Status >", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_Status >=", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusLessThan(String value) {
            addCriterion("Orig_Ref_Order_Line_Status <", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusLessThanOrEqualTo(String value) {
            addCriterion("Orig_Ref_Order_Line_Status <=", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusLike(String value) {
            addCriterion("Orig_Ref_Order_Line_Status like", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusNotLike(String value) {
            addCriterion("Orig_Ref_Order_Line_Status not like", value, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusIn(List<String> values) {
            addCriterion("Orig_Ref_Order_Line_Status in", values, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusNotIn(List<String> values) {
            addCriterion("Orig_Ref_Order_Line_Status not in", values, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusBetween(String value1, String value2) {
            addCriterion("Orig_Ref_Order_Line_Status between", value1, value2, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andOrigRefOrderLineStatusNotBetween(String value1, String value2) {
            addCriterion("Orig_Ref_Order_Line_Status not between", value1, value2, "origRefOrderLineStatus");
            return (Criteria) this;
        }

        public Criteria andRealPriceIsNull() {
            addCriterion("Real_price is null");
            return (Criteria) this;
        }

        public Criteria andRealPriceIsNotNull() {
            addCriterion("Real_price is not null");
            return (Criteria) this;
        }

        public Criteria andRealPriceEqualTo(BigDecimal value) {
            addCriterion("Real_price =", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotEqualTo(BigDecimal value) {
            addCriterion("Real_price <>", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceGreaterThan(BigDecimal value) {
            addCriterion("Real_price >", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Real_price >=", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceLessThan(BigDecimal value) {
            addCriterion("Real_price <", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Real_price <=", value, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceIn(List<BigDecimal> values) {
            addCriterion("Real_price in", values, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotIn(List<BigDecimal> values) {
            addCriterion("Real_price not in", values, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Real_price between", value1, value2, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Real_price not between", value1, value2, "realPrice");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtIsNull() {
            addCriterion("Real_price_amt is null");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtIsNotNull() {
            addCriterion("Real_price_amt is not null");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtEqualTo(BigDecimal value) {
            addCriterion("Real_price_amt =", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtNotEqualTo(BigDecimal value) {
            addCriterion("Real_price_amt <>", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtGreaterThan(BigDecimal value) {
            addCriterion("Real_price_amt >", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Real_price_amt >=", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtLessThan(BigDecimal value) {
            addCriterion("Real_price_amt <", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Real_price_amt <=", value, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtIn(List<BigDecimal> values) {
            addCriterion("Real_price_amt in", values, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtNotIn(List<BigDecimal> values) {
            addCriterion("Real_price_amt not in", values, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Real_price_amt between", value1, value2, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andRealPriceAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Real_price_amt not between", value1, value2, "realPriceAmt");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1IsNull() {
            addCriterion("Orig_sku_prop_1 is null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1IsNotNull() {
            addCriterion("Orig_sku_prop_1 is not null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1EqualTo(String value) {
            addCriterion("Orig_sku_prop_1 =", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1NotEqualTo(String value) {
            addCriterion("Orig_sku_prop_1 <>", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1GreaterThan(String value) {
            addCriterion("Orig_sku_prop_1 >", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1GreaterThanOrEqualTo(String value) {
            addCriterion("Orig_sku_prop_1 >=", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1LessThan(String value) {
            addCriterion("Orig_sku_prop_1 <", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1LessThanOrEqualTo(String value) {
            addCriterion("Orig_sku_prop_1 <=", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1Like(String value) {
            addCriterion("Orig_sku_prop_1 like", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1NotLike(String value) {
            addCriterion("Orig_sku_prop_1 not like", value, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1In(List<String> values) {
            addCriterion("Orig_sku_prop_1 in", values, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1NotIn(List<String> values) {
            addCriterion("Orig_sku_prop_1 not in", values, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1Between(String value1, String value2) {
            addCriterion("Orig_sku_prop_1 between", value1, value2, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp1NotBetween(String value1, String value2) {
            addCriterion("Orig_sku_prop_1 not between", value1, value2, "origSkuProp1");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2IsNull() {
            addCriterion("Orig_sku_prop_2 is null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2IsNotNull() {
            addCriterion("Orig_sku_prop_2 is not null");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2EqualTo(String value) {
            addCriterion("Orig_sku_prop_2 =", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2NotEqualTo(String value) {
            addCriterion("Orig_sku_prop_2 <>", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2GreaterThan(String value) {
            addCriterion("Orig_sku_prop_2 >", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2GreaterThanOrEqualTo(String value) {
            addCriterion("Orig_sku_prop_2 >=", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2LessThan(String value) {
            addCriterion("Orig_sku_prop_2 <", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2LessThanOrEqualTo(String value) {
            addCriterion("Orig_sku_prop_2 <=", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2Like(String value) {
            addCriterion("Orig_sku_prop_2 like", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2NotLike(String value) {
            addCriterion("Orig_sku_prop_2 not like", value, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2In(List<String> values) {
            addCriterion("Orig_sku_prop_2 in", values, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2NotIn(List<String> values) {
            addCriterion("Orig_sku_prop_2 not in", values, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2Between(String value1, String value2) {
            addCriterion("Orig_sku_prop_2 between", value1, value2, "origSkuProp2");
            return (Criteria) this;
        }

        public Criteria andOrigSkuProp2NotBetween(String value1, String value2) {
            addCriterion("Orig_sku_prop_2 not between", value1, value2, "origSkuProp2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table O_Order_Line
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table O_Order_Line
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}