package com.ami.ec.channel.domain.asp;

import java.util.Date;

public class AspIfsUnit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.IFS_Asp_cd
     *
     * @mbggenerated
     */
    private String ifsAspCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Ifs_interface_cd
     *
     * @mbggenerated
     */
    private String ifsInterfaceCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Unit_type
     *
     * @mbggenerated
     */
    private String unitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Unit_id
     *
     * @mbggenerated
     */
    private Long unitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Operate_user_id
     *
     * @mbggenerated
     */
    private Integer operateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ifs_unit.Operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Id
     *
     * @return the value of Ifs_unit.Id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Id
     *
     * @param id the value for Ifs_unit.Id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.IFS_Asp_cd
     *
     * @return the value of Ifs_unit.IFS_Asp_cd
     *
     * @mbggenerated
     */
    public String getIfsAspCd() {
        return ifsAspCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.IFS_Asp_cd
     *
     * @param ifsAspCd the value for Ifs_unit.IFS_Asp_cd
     *
     * @mbggenerated
     */
    public void setIfsAspCd(String ifsAspCd) {
        this.ifsAspCd = ifsAspCd == null ? null : ifsAspCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Ifs_interface_cd
     *
     * @return the value of Ifs_unit.Ifs_interface_cd
     *
     * @mbggenerated
     */
    public String getIfsInterfaceCd() {
        return ifsInterfaceCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Ifs_interface_cd
     *
     * @param ifsInterfaceCd the value for Ifs_unit.Ifs_interface_cd
     *
     * @mbggenerated
     */
    public void setIfsInterfaceCd(String ifsInterfaceCd) {
        this.ifsInterfaceCd = ifsInterfaceCd == null ? null : ifsInterfaceCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Unit_type
     *
     * @return the value of Ifs_unit.Unit_type
     *
     * @mbggenerated
     */
    public String getUnitType() {
        return unitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Unit_type
     *
     * @param unitType the value for Ifs_unit.Unit_type
     *
     * @mbggenerated
     */
    public void setUnitType(String unitType) {
        this.unitType = unitType == null ? null : unitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Unit_id
     *
     * @return the value of Ifs_unit.Unit_id
     *
     * @mbggenerated
     */
    public Long getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Unit_id
     *
     * @param unitId the value for Ifs_unit.Unit_id
     *
     * @mbggenerated
     */
    public void setUnitId(Long unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Status
     *
     * @return the value of Ifs_unit.Status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Status
     *
     * @param status the value for Ifs_unit.Status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Remark
     *
     * @return the value of Ifs_unit.Remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Remark
     *
     * @param remark the value for Ifs_unit.Remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Operate_user_id
     *
     * @return the value of Ifs_unit.Operate_user_id
     *
     * @mbggenerated
     */
    public Integer getOperateUserId() {
        return operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Operate_user_id
     *
     * @param operateUserId the value for Ifs_unit.Operate_user_id
     *
     * @mbggenerated
     */
    public void setOperateUserId(Integer operateUserId) {
        this.operateUserId = operateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ifs_unit.Operate_time
     *
     * @return the value of Ifs_unit.Operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ifs_unit.Operate_time
     *
     * @param operateTime the value for Ifs_unit.Operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}