package com.ami.ec.channel.domain.officialPlugin;

import java.math.BigDecimal;
import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Item_id
     *
     * @mbggenerated
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Item_cd
     *
     * @mbggenerated
     */
    private String itemCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Seller_category
     *
     * @mbggenerated
     */
    private String sellerCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Orig_price
     *
     * @mbggenerated
     */
    private BigDecimal origPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Sale_price
     *
     * @mbggenerated
     */
    private BigDecimal salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Images
     *
     * @mbggenerated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Reserve1
     *
     * @mbggenerated
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Reserve2
     *
     * @mbggenerated
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Reserve3
     *
     * @mbggenerated
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Reserve4
     *
     * @mbggenerated
     */
    private String reserve4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Price_update_time
     *
     * @mbggenerated
     */
    private Date priceUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Stock_update_time
     *
     * @mbggenerated
     */
    private Date stockUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Store_id
     *
     * @mbggenerated
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.ctime
     *
     * @mbggenerated
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.mtime
     *
     * @mbggenerated
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Pj_id
     *
     * @mbggenerated
     */
    private Long pjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Item.Flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Item_id
     *
     * @return the value of Item.Item_id
     *
     * @mbggenerated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Item_id
     *
     * @param itemId the value for Item.Item_id
     *
     * @mbggenerated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Title
     *
     * @return the value of Item.Title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Title
     *
     * @param title the value for Item.Title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Item_cd
     *
     * @return the value of Item.Item_cd
     *
     * @mbggenerated
     */
    public String getItemCd() {
        return itemCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Item_cd
     *
     * @param itemCd the value for Item.Item_cd
     *
     * @mbggenerated
     */
    public void setItemCd(String itemCd) {
        this.itemCd = itemCd == null ? null : itemCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Seller_category
     *
     * @return the value of Item.Seller_category
     *
     * @mbggenerated
     */
    public String getSellerCategory() {
        return sellerCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Seller_category
     *
     * @param sellerCategory the value for Item.Seller_category
     *
     * @mbggenerated
     */
    public void setSellerCategory(String sellerCategory) {
        this.sellerCategory = sellerCategory == null ? null : sellerCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Orig_price
     *
     * @return the value of Item.Orig_price
     *
     * @mbggenerated
     */
    public BigDecimal getOrigPrice() {
        return origPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Orig_price
     *
     * @param origPrice the value for Item.Orig_price
     *
     * @mbggenerated
     */
    public void setOrigPrice(BigDecimal origPrice) {
        this.origPrice = origPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Sale_price
     *
     * @return the value of Item.Sale_price
     *
     * @mbggenerated
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Sale_price
     *
     * @param salePrice the value for Item.Sale_price
     *
     * @mbggenerated
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Images
     *
     * @return the value of Item.Images
     *
     * @mbggenerated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Images
     *
     * @param images the value for Item.Images
     *
     * @mbggenerated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Description
     *
     * @return the value of Item.Description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Description
     *
     * @param description the value for Item.Description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Reserve1
     *
     * @return the value of Item.Reserve1
     *
     * @mbggenerated
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Reserve1
     *
     * @param reserve1 the value for Item.Reserve1
     *
     * @mbggenerated
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Reserve2
     *
     * @return the value of Item.Reserve2
     *
     * @mbggenerated
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Reserve2
     *
     * @param reserve2 the value for Item.Reserve2
     *
     * @mbggenerated
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Reserve3
     *
     * @return the value of Item.Reserve3
     *
     * @mbggenerated
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Reserve3
     *
     * @param reserve3 the value for Item.Reserve3
     *
     * @mbggenerated
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Reserve4
     *
     * @return the value of Item.Reserve4
     *
     * @mbggenerated
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Reserve4
     *
     * @param reserve4 the value for Item.Reserve4
     *
     * @mbggenerated
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Price_update_time
     *
     * @return the value of Item.Price_update_time
     *
     * @mbggenerated
     */
    public Date getPriceUpdateTime() {
        return priceUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Price_update_time
     *
     * @param priceUpdateTime the value for Item.Price_update_time
     *
     * @mbggenerated
     */
    public void setPriceUpdateTime(Date priceUpdateTime) {
        this.priceUpdateTime = priceUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Stock_update_time
     *
     * @return the value of Item.Stock_update_time
     *
     * @mbggenerated
     */
    public Date getStockUpdateTime() {
        return stockUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Stock_update_time
     *
     * @param stockUpdateTime the value for Item.Stock_update_time
     *
     * @mbggenerated
     */
    public void setStockUpdateTime(Date stockUpdateTime) {
        this.stockUpdateTime = stockUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Last_modify_time
     *
     * @return the value of Item.Last_modify_time
     *
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Last_modify_time
     *
     * @param lastModifyTime the value for Item.Last_modify_time
     *
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Create_time
     *
     * @return the value of Item.Create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Create_time
     *
     * @param createTime the value for Item.Create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Store_id
     *
     * @return the value of Item.Store_id
     *
     * @mbggenerated
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Store_id
     *
     * @param storeId the value for Item.Store_id
     *
     * @mbggenerated
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.ctime
     *
     * @return the value of Item.ctime
     *
     * @mbggenerated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.ctime
     *
     * @param ctime the value for Item.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.mtime
     *
     * @return the value of Item.mtime
     *
     * @mbggenerated
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.mtime
     *
     * @param mtime the value for Item.mtime
     *
     * @mbggenerated
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Pj_id
     *
     * @return the value of Item.Pj_id
     *
     * @mbggenerated
     */
    public Long getPjId() {
        return pjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Pj_id
     *
     * @param pjId the value for Item.Pj_id
     *
     * @mbggenerated
     */
    public void setPjId(Long pjId) {
        this.pjId = pjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Item.Flag
     *
     * @return the value of Item.Flag
     *
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Item.Flag
     *
     * @param flag the value for Item.Flag
     *
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}